### ISSUE TITLE
2023.9 not longer able to load integration and can't update

### ISSUE THREAD

**Issue by KoljaWindeler** [kamaradclimber/heishamon-homeassistant#100]
Hi, I've just update to 2023.9 and get: 

Logger: homeassistant.setup
Source: setup.py:379
First occurred: 16:41:43 (1 occurrences)
Last logged: 16:41:43

Unable to prepare setup for platform aquarea.sensor: Platform not found (No module named 'homeassistant.helpers.template_entity').

I've tried to update but i get this:

You are running Home Assistant version '2023.9.0', but this repository requires minimum version '2023.9' to be installed.

**Comment by lolobar** [comment]
I have the same Problem

**Comment by Bucky2k** [comment]
Hmm, cannot get it to update from HACS - still inoperable and showing the version error... Any tips?

**Comment by kamaradclimber** [comment]
Hello @Bucky2k ,

you need https://github.com/kamaradclimber/heishamon-homeassistant/releases/tag/1.0.10 to have the fix.
Which difficulty do  you face to update?

**Comment by markface69** [comment]
> Hello @Bucky2k ,
> 
> you need https://github.com/kamaradclimber/heishamon-homeassistant/releases/tag/1.0.10 to have the fix. Which difficulty do you face to update?

Ok

**Comment by Bucky2k** [comment]
I can't get it to download and install 1.0.10 for some reason. Still getting:

![Screenshot_20230907_205354_Home Assistant](https://github.com/kamaradclimber/heishamon-homeassistant/assets/67497826/9d68e5c4-86be-452e-8164-892e3f439b6e)

**Comment by markface69** [comment]
Thank you . ok it works for me. I extracted heishamon-homeassistant-1.0.10 and manually copied the aquarea directory into custom_components. Using hacs doesn't work for me copying it manually yes everything is ok

> > Hello @Bucky2k ,
> > you need https://github.com/kamaradclimber/heishamon-homeassistant/releases/tag/1.0.10 to have the fix. Which difficulty do you face to update?
> 
> Ok

Thank you . ok it works for me. I extracted heishamon-homeassistant-1.0.10 and manually copied the aquarea directory into custom_components. Using hacs doesn't work for me copying it manually yes everything is ok

**Comment by kamaradclimber** [comment]
It seems hacs is a bit strict on version comparison, it is likely to be fixed now (with 1.1.2). I've just updated with success on my own installation.
Thanks for the report!

**Comment by KoljaWindeler** [comment]
Thanks, yes confirmed working

**Comment by lolobar** [comment]
Thank yo for the quick Help.
