### ISSUE TITLE
Aquarea Domestic Water Heater unavailable

### ISSUE THREAD

**Issue by omenukas** [kamaradclimber/heishamon-homeassistant#102]
After updating Heishamon to version 1.1.2, Aquarea Domestic Water Heater stopped showing.

Should I look for the problem in the settings, or is it a version bug?

![image](https://github.com/kamaradclimber/heishamon-homeassistant/assets/122688908/e8019663-6a72-459f-a895-96c32abbdf63)

**Comment by kamaradclimber** [comment]
Hello, 

it is an intended change of https://github.com/kamaradclimber/heishamon-homeassistant/releases/tag/1.1.0. You’ll find the water heater under a new entity (with exactly the same name and entity_id)
