### ISSUE TITLE
New DHW boiler entity - status none

### ISSUE THREAD

**Issue by Bucky2k** [kamaradclimber/heishamon-homeassistant#103]
Hi,

is it correct, that for now the boiler is shown with status "none"
![Screenshot_20230908_083925_Home Assistant](https://github.com/kamaradclimber/heishamon-homeassistant/assets/67497826/7499cf73-abe0-40a1-9b46-b601e425dc18)

**Comment by Bucky2k** [comment]
As many HP users are only heating the water to 44-50°C - can't the Eco range simply be extended to e.g. 42°C?

**Comment by kamaradclimber** [comment]
Trying to read a bit about this, it seems 49°C is the minimal recommended temperature to avoid legionnalla to develop.

I think however you are right on the fact that we should not display "none" when outside of a known preset, especially if presets are only a single temperature point. I propose to "detect" preset on a range of temperature (and when a preset is selected, we put a target temperature within that range).

What would you think of having the following presets:

| Preset | Target temperature if preset is activated through HA | Accepted target temperature for that preset |
|----|----|----|
|`High-Demand`| 60 | 55-65 |
| `Eco` | 49 | 49-55 |
| `Super-Eco (dangerous)` | 46 | 44-58 |

**Comment by Bucky2k** [comment]
Yes, sounds good. The topic of Legionella in small water systems less than 400 liters is an ambiguous one. You can read days about it, but never come to a point where you are entirely certain. In Switzerland they consider changing this rule as it seems to make little to none difference. Main argument: Even if you keep the boiler above 50°C, the Legionella usually start growing in the pipes where you never reach this temperature consistently. Bottom line: Very many heatpump users stay at ~45-48°C for the benefit of not using the electric heater and to raise COP levels.

I recommend to call it ECO+ or Super ECO without "dangerous"

**Comment by Bucky2k** [comment]
Another point: Many have not an e.g. 300l boiler with fresh water, but a large buffer where a separate heat exchanger is using it for hot water generation. There you don't have the Legionella risk and usual setpoint is again 45°C

**Comment by geduxas** [comment]
For example, H series heatpump with integrated boiler, will heat up DHW to 51° without any problem.. 52 and above it will require more energy.. and from 55° it will require additional heater to take it..  i usualy hold 37-51 in my system.

**Comment by Bucky2k** [comment]
51°C without problem yes, but still you end up with much lower average COP. Therefore the ones with freshwater heat exchanger and big buffer go as low as comfort allows. Again - all good, I would just not put "dangerous"

**Comment by kamaradclimber** [comment]
As we can see from our discussion, there is no consensus indeed!
I'll try to add the feature with reasonable settings
