### ISSUE TITLE
Fail to start integration after upgrade to Home Assistant 2023.9.0

### ISSUE THREAD

**Issue by stjerno** [kamaradclimber/heishamon-homeassistant#104]
After the upgrading to the latest version of HA the integration fail to start.

Log only shows:

Unable to prepare setup for platform aquarea.sensor: Platform not found (No module named 'homeassistant.helpers.template_entity').

Enabling debug log does not provide further info.
I'm on the latest version of the integration too.

**Comment by kamaradclimber** [comment]
Hello, are you sure you are on the latest version available?
This issue was corrected by https://github.com/kamaradclimber/heishamon-homeassistant/commit/3ed7acadfe1f7b076fe938c76b0b7b182c72046b, present in all version since 1.0.10 of this integration.

**Comment by stjerno** [comment]
Very embarrassing - had an issue with the upgrade yesterday, and had problems restoring from previous backup so rolled back from on older backup.
Could see I now was on 1.0.9 - an upgrade and problem was solved.

Thank you.

**Comment by stjerno** [comment]
Updated to latest version of the integration.
