### ISSUE TITLE
Integration stops working if an update to HA 2023.9.0 is performed

### ISSUE THREAD

**Issue by scroom** [kamaradclimber/heishamon-homeassistant#105]
As described above. Because of the problem I've restored the update of the previous installed version and forgot to save the logs.

**Comment by scroom** [comment]
Tried to make an update again (HA 2023.9.1) with the same result. This time if saved the log before restoring the backup:

> Logger: homeassistant.setup
Source: setup.py:379
First occurred: 11:38:56 (1 occurrences)
Last logged: 11:38:56

> Unable to prepare setup for platform aquarea.sensor: Platform not found (No module named 'homeassistant.helpers.template_entity').

**Comment by geduxas** [comment]
@scroom did you update integration itself?

**Comment by scroom** [comment]
My fault! Thought that the update would be possible to perform before updating HA. Sorry!

**Comment by kamaradclimber** [comment]
Indeed @scroom , I put a constrain on the integration to forbid integration update before HA being in the correct version. It makes the process tedious (you have to upgrade HA, notice theintegration has an available update and restart HA again).
I'll try to fix this by making the integration backward compatible
