### ISSUE TITLE
Missing sensors with HA 2023.9

### ISSUE THREAD

**Issue by netmb** [kamaradclimber/heishamon-homeassistant#107]
I think there is an issue with this component and Home-Assistant 2023.9. 
I get the following error on startup:

`2023-09-09 12:14:01.019 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform aquarea.sensor: Platform not found (No module named 'homeassistant.helpers.template_entity').`

This happens in Version 2023.9 and 2023.9.1. HA-Version 2023.8 its working without problems.

**Comment by geduxas** [comment]
Update integration!

**Comment by kamaradclimber** [comment]
Hello @netmb , as suggested by @geduxas , you should update the integration to have a version greater than 1.0.10.
I'll close the issue (and create an issue template to make it clearer that issue should be reported once it has been reproduced with latest version of the integration ;) )

**Comment by netmb** [comment]
Sorry guys ! I did not check manually for a new version, because HACS normally shows the information when a new version is available. Stupid me.

**Comment by kamaradclimber** [comment]
You are clearly not stupid, see https://github.com/kamaradclimber/heishamon-homeassistant/issues/105#issuecomment-1712486013. I made sure other users won't have the same issue (they will be able to update integration before updating HA)
