### ISSUE TITLE
Water heater

### ISSUE THREAD

**Issue by meavric** [kamaradclimber/heishamon-homeassistant#111]
Hi
After update to last version (1.1.4) i have problem with encia: panasonic_heat_pump_main_dhw_target_temp - encia dose not exist and i dont see water temperature and cannot change it by button.
How fix it?
![ss](https://github.com/kamaradclimber/heishamon-homeassistant/assets/56772416/4ba0d470-546c-4fa6-b4a8-46a775860552)

**Comment by kamaradclimber** [comment]
Hello,
https://github.com/kamaradclimber/heishamon-homeassistant/releases/tag/1.1.0 shows the climate entity used to represent the water heater has been changed. You should find an entity called sometihng like `water_heater.panasonic_heat_pump_...`. You can safely delete the old entity.

**Comment by meavric** [comment]
Hi,
ok but tell me how fix button to manage this parameter how was it in old version?

**Comment by geduxas** [comment]
> water_heater.panasonic_heat_pump_

change device in card from ```**climate**.panasonic_heat_pump_...``` to ``**`water_heater**.panasonic_heat_pump_...```

**Comment by meavric** [comment]
I cannot change it, i dont see this entity
My xml config look that:
  - square: false
    columns: 3
    type: grid
    cards:
      - type: thermostat
        name: CWU
        entity: water_heater.panasonic_heat_pump_main_dhw_target_temp
      - type: thermostat
        entity: climate.panasonic_heat_pump_main_z1_temp
        name: Grzejniki
      - type: thermostat
        entity: climate.panasonic_heat_pump_main_z2_temp
        name: Podłogówka

What type set for water_heater.panasonic_heat_pump_main_dhw_target_temp ?

**Comment by kamaradclimber** [comment]
I don’t see any water heater specific card on https://www.home-assistant.io/dashboards/cards. You can likely try with `entity` and possibly request a water_heater card to HA frontend dev

**Comment by geduxas** [comment]
indeed, I though thermostat cards are compatible to water_heater element.. but I was wrong..

**Comment by kamaradclimber** [comment]
Climate entities receveid a lot of attention recently (https://www.home-assistant.io/blog/2023/10/04/release-202310/#new-tile-card-features-for-climate-entities), maybe devs could be receptive to requests about water heater as well.

**Comment by geduxas** [comment]
@kamaradclimber did you see my ideas for water heater control earlier? :) truly i didn't find right now in which topic i had written all about :D

**Comment by whulshof** [comment]
I'm having the same problem. Is anybody acting on it?

**Comment by geduxas** [comment]
> I'm having the same problem. Is anybody acting on it? I think the former setup as climate entity was quite OK. What is the advantage of a separate water_heater class?

HomeAssistant decided to do that :) i think it's proper way to use it instead of climate component.. and yes climate i think is more suitable for today's use.. also please take time to discuss in #145  for rework of water heater implementation

**Comment by kamaradclimber** [comment]
For now I'll keep the water heater model, hoping HA dev will put some attention to it. I'll have a look at #145
