### ISSUE TITLE
TOP77 - Heating_Off_Outdoor_Temp - not adjustable

### ISSUE THREAD

**Issue by frankol** [kamaradclimber/heishamon-homeassistant#125]
Hi,

this topic ist writable in HeishamonGo. Can you make it here too?

**Comment by kamaradclimber** [comment]
Hello, thanks for opening a feature request.

I was not really aiming for compatibility with GoHeishamon. We can try for sure but I'm not sure I can support it easily because that's not a setup I'm using at all.

Could you provide documentation I could look at to see how the topic corresponding to TOP77 is writable please?

**Comment by geduxas** [comment]
> Hello, thanks for opening a feature request.
> 
> I was not really aiming for compatibility with GoHeishamon. We can try for sure but I'm not sure I can support it easily because that's not a setup I'm using at all.
> 
> Could you provide documentation I could look at to see how the topic corresponding to TOP77 is writable please?

HeishamonGo is direct port from heishamon (arduino) to Go language, it's used same technic and protocol as heishamon.. so same as applies to heisha should fit and heishamongo..

**Comment by kamaradclimber** [comment]
Thanks for the precision. I'm not sure to see if the topic for TOP77 is writable in vanilla Heishamon so it seems to be specific to HeishamonGo, unless I'm mistaken.

**Comment by geduxas** [comment]
> Thanks for the precision. I'm not sure to see if the topic for TOP77 is writable in vanilla Heishamon so it seems to be specific to HeishamonGo, unless I'm mistaken.

I have made it available in Igor repository, so it will be after Igor will release. So it's still in beta :) 

https://github.com/Egyras/HeishaMon/issues/351

**Comment by frankol** [comment]
> 
> HeishamonGo is direct port from heishamon (arduino) to Go language, it's used same technic and protocol as heishamon.. so same as applies to heisha should fit and heishamongo..

the difference is just that you dont need a extra yaml translation file because the values are translated directly to readable output, like Operating_Mode_State. Instead of numbers it will come with the name-values already.

Regarding TOP77: this is the topics.yaml part for it:
- sensorName: Heating_Off_Outdoor_Temp
  codec:
    - decodeFunction: getIntMinus128
      encodeFunction: setIntPlus128
      offset: 83
  displayUnit: °C
  category: config
  min: 5
  max: 35
  step: 1

**Comment by frankol** [comment]
> 
> I have made it available in Igor repository, so it will be after Igor will release. So it's still in beta :)
> 
> [Egyras/HeishaMon#351](https://github.com/Egyras/HeishaMon/issues/351)

thank you very much!
