### ISSUE TITLE
Demand control 

### ISSUE THREAD

**Issue by Safs** [kamaradclimber/heishamon-homeassistant#127]
Demand control still not working. Now I can move slider, but nothing to happening. Slider always return to 100% after some time and is not possible to set back to 100%, because it is already on 100%...
I tred to get some logs:

```
2023-10-12 08:28:48.457 DEBUG (MainThread) [custom_components.aquarea.number] Changing Demand Control to 72.0 (sent to panasonic_heat_pump/commands/SetDemandControl)
2023-10-12 08:28:49.313 DEBUG (MainThread) [custom_components.aquarea.number] Changing Demand Control to 40.0 (sent to panasonic_heat_pump/commands/SetDemandControl)

```
```
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:762
First occurred: 08:15:30 (1 occurrences)
Last logged: 08:15:30

Entity number.panasonic_heat_pump_main_fakedemandcontrol (<class 'custom_components.aquarea.number.HeishaMonMQTTNumber'>) does not have a platform, this may be caused by adding it manually instead of with an EntityComponent helper, please report it to the custom integration author
```

**Comment by kamaradclimber** [comment]
I think there are two issues here:
- the first one is because the mqtt topic prefix for PCB command seems to be `optional` instead of `commands` (which is used for regular commands). I'll fix this.
- the second one is a warning that appear when we initialize the entity, for some reason the platform is not setup yet (it is later but the warning is configured to display once). I'll check how to fix this

**Comment by giedriuskilcauskas** [comment]
I've also noticed that Demand Control entity id is: number.panasonic_heat_pump_main_none
which doesn't sound right

**Comment by kamaradclimber** [comment]
It's a hack I've used in previous version because there is no mqtt topic to read the data. Recent version of the integration have a more meaningful name but HA does not change entity_id once it has been created. New users of the integration will have a better naming.

**Comment by Safs** [comment]
When I publish topic "panasonic_heat_pump/commands/SetDemandControl", it is working...
According to [Heisamon](https://github.com/Egyras/HeishaMon/blob/master/MQTT-Topics.md), it is correct syntax...

**Comment by kamaradclimber** [comment]
Documentation is not super clear for me (`commands` are used for regular commands but documentation for optionalpcb topics is less clear regarding commands).
How do you compute the value you put manually in "panasonic_heat_pump/commands/SetDemandControl" topic?

**Comment by Safs** [comment]
As I can see, commands sends correctly and working, but that demand control slider does not stay on position that is set.

**Comment by Safs** [comment]
![image](https://github.com/kamaradclimber/heishamon-homeassistant/assets/7047586/2e33dcbe-e794-4c1c-b4b3-783fe1fd1434)
After refresh, slider is got back to 100%

**Comment by Safs** [comment]
Yes, I understand. Nice to be, if simply slider stay in last set position in HA.

**Comment by kamaradclimber** [comment]
https://github.com/kamaradclimber/heishamon-homeassistant/pull/130 should do it

**Comment by kamaradclimber** [comment]
https://github.com/kamaradclimber/heishamon-homeassistant/releases/tag/1.2.5 should fix everything described

**Comment by geduxas** [comment]
also could anyone of you confirm that demand control is working better than setting pump in desired silent mode?
@Safs @giedriuskilcauskas

**Comment by Safs** [comment]
Hard to say, I did not compare demand control with silent modes, because for me demand control working well. I define four modes in my automations, 25, 50, 75, and 100% power. Automations is configured  to send commands depend on prices of electricity. In my opinion, demand control working well.

**Comment by geduxas** [comment]
> Hard to say, I did not compare demand control with silent modes, because for me demand control working well. I define four modes in my automations, 25, 50, 75, and 100% power. Automations is configured to send commands depend on prices of electricity. In my opinion, demand control working well.

And did you try to set values for 20, 40, 60% does they match same 25, 50,  75 modes? :)  i think demand control is not so sensitive.. and i almost 80% shure that values ar tied to silent mode setting.. silent 1 (around 75%) silent 2 (around 50%) silent 3 (around 25%) , ant that value gives feedback.. so os there any reason to use direct demand control?  I have external PCB with 0-10V control.. i tried to test different values, and unable to get that precision.

**Comment by Safs** [comment]
Yes, you are right, demad control can set not lower than 30% of power.

**Comment by Safs** [comment]
I was try to play around demand control. No all so bad.
I set heatpump to "powerful" mode, and then I playing with demand contro slider. 
As info for power I take current. From the manual, max current is 11.9A, so, this value corresponds to 100% of power.
The min power with demand control what I can set is 25%. After that, I was able to increase the power in 5% increments to the power actually needed at the time.
So, it woud be nice, if that slider will be with resolution of 5%. Is it possible to implement that?

**Comment by geduxas** [comment]
5% is default step for demand control, so you successfully managed to step by 5%?
![Screenshot_2023-10-11-22-22-47-12_e2d5b3f32b79de1d45acd1fad96fbb0f](https://github.com/kamaradclimber/heishamon-homeassistant/assets/18700450/0e796ba5-453b-4040-b21b-9caa5944920a)

**Comment by Safs** [comment]
Yes, starting from 25%. If I set for example 45%, power is remine same, (from current) 45%.

**Comment by geduxas** [comment]
> Yes, starting from 25%. If I set for example 45%, power is remine same, (from current) 45%.

Ok so 10/15/25% are truly not used? Maybe do you have some graphs by increasing demand control? Smi have tested with mine too, but didn't notice'd 5% precision, maybe my tests was too short. I only noticed 3 or 5 different behavior, but as result i watched only frequency of compressor.  Yes current would be better choice for that :) also powerful mode! As i tested only on heating DWH. 

Also what's are drawbacks of using demand control, if i leave 25% for demand control and heat DWH to 52° it's impossible to reach that value.. so pump will try to heat till reaches its timeout. Also from (if i remember right) from around 40° (dwh) cop drastically falls to 0.2 :D which could bring a lot of troubles for someone.. i think there should also be implemented some control logic fir that too

**Comment by Safs** [comment]
First, you need to get the heat pump working with a high power demand, then you can play with the demand control, otherwise, if the pump does not need power, it does not respond to power reduction commands either...
I created automation, when heatpump is in DHW mode, then damand control is set to 100%., because of problem that you mention. 
There is graph, I changed power by 5%... Start at 35%, then 30, 25, 40%
![image](https://github.com/kamaradclimber/heishamon-homeassistant/assets/7047586/f0726445-eb00-495e-a325-5c9b481cddc5)

**Comment by Safs** [comment]
> So, it woud be nice, if that slider will be with resolution of 5%. Is it possible to implement that?

Can anybody do this?

**Comment by kamaradclimber** [comment]
https://github.com/kamaradclimber/heishamon-homeassistant/pull/142 should do it but I don’t have time to test it at the moment.
