### ISSUE TITLE
Heishamon breaking change FW3.2 --> Energy to Power

### ISSUE THREAD

**Issue by Bucky2k** [kamaradclimber/heishamon-homeassistant#131]
The following Topics will change their naming from Energy to Power after Heishamon 3.2 firmware upgrade. Are we already catching this breaking change?

TOP15	Heat_Energy_Production
TOP16	Heat_Energy_Consumption
TOP38	Cool_Energy_Production
TOP39	Cool_Energy_Consumption
TOP40	DHW_Energy_Production
TOP41	DHW_Energy_Consumption

Br
bucky2k

**Comment by MEKadan** [comment]
Yes, tried 3.3 and it breaks the integration. To add to the above list, also the heat pump model is not transmitted correctly, TOP92

**Comment by kamaradclimber** [comment]
Hello, I'll close this issue since Energy/Power is supported in latest pre-release (https://github.com/kamaradclimber/heishamon-homeassistant/releases/tag/1.3.0) of this integration.
@MEKadan could you open a separated issue with more details so I can investigate?

**Comment by geduxas** [comment]
> Hello, I'll close this issue since Energy/Power is supported in latest pre-release (https://github.com/kamaradclimber/heishamon-homeassistant/releases/tag/1.3.0) of this integration. @MEKadan could you open a separated issue with more details so I can investigate?

It could be that heishamon recently added more pumps to it's own code.. integration models.py is not updated 28 models vs 37 in heishamon.

**Comment by MEKadan** [comment]
> > Hello, I'll close this issue since Energy/Power is supported in latest pre-release (https://github.com/kamaradclimber/heishamon-homeassistant/releases/tag/1.3.0) of this integration. @MEKadan could you open a separated issue with more details so I can investigate?
> 
> It could be that heishamon recently added more pumps to it's own code.. integration models.py is not updated 28 models vs 37 in heishamon.

Yes, that's the case. 
I could not get the updater script presented in `models.py` to work since I'm on win, but no big deal, it's easy to add your model manually when you know your model code e.g. from MQTT

**Comment by kamaradclimber** [comment]
https://github.com/kamaradclimber/heishamon-homeassistant/releases/tag/1.3.1 contains all models. Thanks
