### ISSUE TITLE
Missing XTOP values V1.3.2 - HeishaMon V.3.2.2 - HP L-series

### ISSUE THREAD

**Issue by n4rrOx** [kamaradclimber/heishamon-homeassistant#141]
👋 Hello, thanks for reporting a bug. Please make sure you have read/completed the following template ✅

** Versions **

- Home Assistant version (for instance 2023.9): 2023.10.5
- This integration version (for instance 1.1.0): 1.3.2

**Describe the bug**
Running HeishaMon on "official Board" with V3.2.2 attached to a L-series HP.
XTOP values are not shown in Integration.
COP is not correct.

HeishaMon publishs XTOP over MQTT and they are received from HA.
Screenshots could be found here: https://github.com/Egyras/HeishaMon/issues/370#issuecomment-1774922835
Reboot of HA was done after Update of Integration.
Also Delete of HA and HACS Integration (reboot) and adding again was not successful.

**To Reproduce**
see above

**Expected behavior**
XTOP values should be available as well as the correct COP.

**Screenshots**
If applicable, add screenshots to help explain your problem:
https://github.com/Egyras/HeishaMon/issues/370#issuecomment-1774922835

**Comment by kamaradclimber** [comment]
Hello, thanks for reporting.
Those topics are not documented at the moment. I'll see what I can do to integrate them.

**Comment by n4rrOx** [comment]
Hi, sorry for writing you in the closed topic again.

Thanks for the V1.3.3 Update!
First it looked good after Update & Reboot for the "normal" Power entities (heat, dhw, cooling) but not for total consumption/Produktion.
But after a few minutes values went back to the former ones:
![IMG_20231023_235427_37](https://github.com/kamaradclimber/heishamon-homeassistant/assets/110202968/0541b9b0-dec1-4f9b-bfbc-ff240305ccf3)

E.g. heat consumption went fromm -200 to 15 and then back to -200W.
Total consumption from -1200 to -1185W (-1200+15W):
![IMG_20231023_235446_854](https://github.com/kamaradclimber/heishamon-homeassistant/assets/110202968/eac8df20-4fac-4a82-87db-72875654eec4)

The HeishaMon values:
![IMG_20231023_235500_423](https://github.com/kamaradclimber/heishamon-homeassistant/assets/110202968/16eb850f-2a7c-41ee-bf7b-9a5bde11b3cb)

**Comment by kamaradclimber** [comment]
Should be fixed in 1.3.5, thanks for the report

**Comment by egrigat** [comment]
Thank you for 1.3.5. Just tried this because I had a similar problem. It seems that from somewhere this code is building a sum from entities I cannot find in homeassistant. No negative values here. Even when the heatpump is off I have the consumption and production showed in the screenshot.

I had, before there was a HACS integration, the heishamon.yaml I've a couple of hours ago, before updating to 1.3.5. Before I reinstalled heishamon integration, but no success. I cannot find entities with 400W consumption and 2.600W production like in the screenshot.

![image](https://github.com/kamaradclimber/heishamon-homeassistant/assets/113016835/b9662081-1fcf-4f12-8c8b-6ea611fe2b3c)

**Comment by kamaradclimber** [comment]
By any chance, would have updated heishamon itself to version >= 3.2 ?
If that's the case, my guess is that you still have the "old" mqtt topics present in your MQTT server. This integration sums everything (maybe that's a mistake) from the old mqtt topics, the new ones and the ones used specifically for K/L series.

**Comment by egrigat** [comment]
Yes, Heishamon is on 3.2
I'm not very familiar with MQTT: Is this a task for me to delete anything or should I address this in the heishamon gitub project? Seems to be static values the 400 and 2600. Just started the pump in power mode and the deviation is always the same.

**Comment by egrigat** [comment]
found it in MQTT console:
![image](https://github.com/kamaradclimber/heishamon-homeassistant/assets/113016835/768f6e44-863a-43e1-b987-b301790c9e1c)

the "energy" entries are old, correct?

**Comment by kamaradclimber** [comment]
Yes energy has been replaced by Power. The technique is simply to remove those topics, or send a 0 value to them.
But if you have this issue, others will have it. I need to find a solution so if you can wait ~15min, I'll propose a patch

**Comment by geduxas** [comment]
> Yes energy has been replaced by Power. The technique is simply to remove those topics, or send a 0 value to them. But if you have this issue, others will have it. I need to find a solution so if you can wait ~15min, I'll propose a patch

@kamaradclimber please don't go out off your mind.. but in 3.2.3 Igor has renamed and extra power

**Comment by egrigat** [comment]
Thank you very much for your help. I just installed MQTT Explorer and set 0 to the following topics:
panasonic_heat_pump/main/Heat_Energy_Production
panasonic_heat_pump/main/Heat_Energy_Consumption

After the restart (heishamon and homeassistant) it's still fine. Solved for me. Thank you for your help!

**Comment by geduxas** [comment]
> Thank you very much for your help. I just installed MQTT Explorer and set 0 to the following topics: panasonic_heat_pump/main/Heat_Energy_Production panasonic_heat_pump/main/Heat_Energy_Consumption
> 
> After the restart (heishamon and homeassistant) it's still fine. Solved for me. Thank you for your help!

You should delete them. It won't be used anymore. Delete all topic's which contains *_Energy_*

**Comment by kamaradclimber** [comment]
> You should delete them. It won't be used anymore. Delete all topic's which contains Energy
That's the cleaner course. However, if every user face the same situation we should probably find a workaround. I've tried #148 , let's see if it works for users.

**Comment by egrigat** [comment]
Quote from changelog:
> Topics are ordered from most specific to least specific. We take the first set of 3 topics that have at least a value.

From my point of view the problem would still be there when the pump/compressor is off. Consumption/production in the "power" topics are zero then. But the code will still sum up the "energy" topics, right?

**Comment by longtom99** [comment]
I can't see the XTOP values in Home Assistant.
What do i wrong?
In MQTT Explorer: panasonic_heat_pump/extra/Heat_Power_Consumption_Extra

**Comment by kamaradclimber** [comment]
@longtom99 you should see the values under the `Aquarea Heat Power Consumed` entity.
If you don't, could you open a new issue please with relevant info:
- version of heishamon
- version of heishamon-homeassistant
- the value you have in MQTT topics
- the value you have in home assistant
- any warning you see in home assistant logs
- anything that seem relevant to the issue.
