### ISSUE TITLE
Pump totals are counted wrong

### ISSUE THREAD

**Issue by hannut** [kamaradclimber/heishamon-homeassistant#146]
👋 Hello, thanks for reporting a bug. Please make sure you have read/completed the following template ✅

** Versions **

- Home Assistant version (for instance 2023.9): 2023.10.5
- This integration version (for instance 1.1.0): 1.3.3

> [!IMPORTANT]
> It's even better if you can make sure you are using the lastest version for the integration (https://github.com/kamaradclimber/heishamon-homeassistant/releases)

**Describe the bug**

Pump total consumption and Pump total production show much larger values than they should. This could be related to the 3.2 new topic names

**To Reproduce**

**Expected behavior**
Correct values for sensors

**Screenshots**

![2023-10-25T08:46:29,418935259+03:00](https://github.com/kamaradclimber/heishamon-homeassistant/assets/10574295/baa8f96b-1684-4cde-b1c4-6618b6976e19)

**Comment by geduxas** [comment]
Yes it's related to and duplicates #141.
