### ISSUE TITLE
Pump total consumption and production entities show incorrect value

### ISSUE THREAD

**Issue by tjani8** [kamaradclimber/heishamon-homeassistant#149]
- Home Assistant version 2023.10.3
- This integration version 1.3.6
- Heishamon firmware version 3.2.2
- J-series heatpump

When I updated integration from 1.2.5 to the latest version (and update Heishamon firmware same time) then the Aquarea pump total consumption & production show incorrect value.
Before the update these entities show the same value as Aquarea heat power consumed & produced. I don't use cooling or DHW modes, that entities show zero.

See screenshot.
Total consumption shows 800w more than value in heat power consumed and production soo much more than value in heat power produced.
Where these 800w comes?

**Expected behavior**
That total sensors show the same values as before the update.

**Screenshots**
![kuva](https://github.com/kamaradclimber/heishamon-homeassistant/assets/122315491/2b2b661a-0a8a-4a00-bce0-13f8b5637cf5)

**Comment by kamaradclimber** [comment]
Hello,

thanks for the detailed bug report. It seems very close to what was reported in #141 latest messages.

Since you run the last version of the integration and firmware, it should not happen but let's investigate.

If you set debug log for the integration

```
logger:
  default: warning
  logs:
    custom_components.aquarea: debug
```

you should see lines such as `Chunk [...] has data`. I would expect to see lines with `Chunk 1 [...] has data`. Could you confirm this? Also the [...] should be a list of 3 items (if you see more there is a bug in the integration).

**Comment by kamaradclimber** [comment]
https://github.com/kamaradclimber/heishamon-homeassistant/releases/tag/1.3.7 has a good chance of fixing the issue :facepalm:

**Comment by tjani8** [comment]
Thank you.
After that update the sensors give correct values.

**Comment by geduxas** [comment]
@kamaradclimber small hint, maybe it will help. 
So for old deprecated values in \_energy\_ topics they should be totally ignored if pressents \_power\_ topic. (Direct replacement) 
As for xtopic they're will be published only on K/L pumps.. so it's should replace normal main\/\*\_power\_\* if pressents. So again, direct replacement.. 
And from heishamon 3.2.3! Extra topics renamed to \*\_power\_\*\_Extra 

Maybe it might help :)

**Comment by tjani8** [comment]
Now I noticed that COP show 3,0x when power consumption and production is zero.
![kuva](https://github.com/kamaradclimber/heishamon-homeassistant/assets/122315491/d6ed993a-c2eb-4785-93aa-07d830d5a1fe)

**Comment by kamaradclimber** [comment]
@tjani8 thanks for reporting, next version of the integration will fix this.

**Comment by geduxas** [comment]
> > And from heishamon 3.2.3! Extra topics renamed to __power___Extra
> 
> @geduxas , I 'm not sure to understand what will happen in 3.3. More renaming?

3.2.3 still in PR

https://github.com/Egyras/HeishaMon/pull/397/files
