### ISSUE TITLE
Additional Entities for e.g. Defrost State, DHWSetTemp as Sensor only

### ISSUE THREAD

**Issue by mieschc** [kamaradclimber/heishamon-homeassistant#151]
**Is your feature request related to a problem? Please describe.**
Maybe there is a Home Assistant Workaround which I am not aware about (I am not a pro ;)). If I use the current entities for e.g. Defrost State or DHWSetTemp it is displayed as switch, drop down menu or similiar. Means I actually can change it on my dashboard or e.g. on my cellphone. For some values I do not want to be able to change it, just that the current state is displayed (e.g. defrost state) to prevent accidently changing values, especially when using small cellphone display (I just activated the defrost procedure two times because I clicked accidentily on the entity widget on my cellphone)

**Describe the solution you'd like**
Additional entitities as sensor only for DHWSetTemp, Defrost State, Heat Request Shift Temp, Heat Pump Mode, Heat Pump Power State, Quiet Mode Level etc.

**Describe alternatives you've considered**
At the moment I use entries from the [heishamon.yaml](https://github.com/Egyras/HeishaMon/blob/master/Integrations/Home%20Assistant/heishamon.yaml) for above entities to have it as sensor only. Would be nicer to have everything in only one integration.

**Additional context**
Please let me know if there is any other easy workaround within Home Assistant I am not aware off.

Brgds

**Comment by geduxas** [comment]
For that you can use history graph. It will show in graph when it was last time activated..

**Comment by geduxas** [comment]
Also "glance card" from HA could be suitable

![Screenshot_2023-10-28-19-35-16-56_c3a231c25ed346e59462e84656a70e50](https://github.com/kamaradclimber/heishamon-homeassistant/assets/18700450/0faf99f8-d2a2-4ea1-b760-054ee18c7ea3)

**Comment by kamaradclimber** [comment]
Hello,

that's an interesting use case, thanks for reporting it.
I'm not fond of adding more entities (there are already so many!). However I completely understand the need to have read-only values. I think you could open a discussion on https://community.home-assistant.io to understand how other people are dealing with this. I assume there is a solution based on UI elements.

**Comment by kamaradclimber** [comment]
[https://community.home-assistant.iohttps://community.home-assistant.io/t/is-it-possible-to-show-an-entity-as-read-only-in-ui/564348](https://community.home-assistant.io/t/is-it-possible-to-show-an-entity-as-read-only-in-ui/564348) suggest to use the markdown card

**Comment by mieschc** [comment]
I can understand that adding additional entitites is not the best way to keep the amount as low as possible. I guess easiest way will be template sensors, because I do not want to use it only on the dashboard, but e.g. as widget on the cellphone / tablet too. I will give it a try to find out how to configure template sensors from the integration provided entitites.

**Comment by Safs** [comment]
Me also, Defrost State entitite will be  nice to add.

**Comment by geduxas** [comment]
2 options in HA,
1. Conditional card,
2. History graph card.

![Screenshot_2023-10-31-18-33-50-29_c3a231c25ed346e59462e84656a70e50](https://github.com/kamaradclimber/heishamon-homeassistant/assets/18700450/bb00ea0c-c3db-4873-8a0c-108cec626b23)


For option 1  you use regular entity
And set no action on tap or long hold.. or use as desired
Highly customizable.

![Screenshot_2023-10-31-18-34-44-77_c3a231c25ed346e59462e84656a70e50](https://github.com/kamaradclimber/heishamon-homeassistant/assets/18700450/4db95967-c386-47f9-9cae-cd3d8af325c3)

For option 2, use regular entity and set desired status history.. for 1h. For or as you desired..

![Screenshot_2023-10-31-18-34-14-95_c3a231c25ed346e59462e84656a70e50](https://github.com/kamaradclimber/heishamon-homeassistant/assets/18700450/576bebba-73a2-4625-a1dc-b31d75bbc045)

**Comment by Safs** [comment]
Ok, thanks.

**Comment by kamaradclimber** [comment]
Hello all, I see two options:
- people interested in read-only entities usually want this to avoid changing values by mistake. It can be done with a bit of work in a dashboard
- or we could create read-only entities for all switches. To avoid overloading HA with entities that are not necessary, I would propose to have those entities hidden by default (users would have to manually activate them one by one).

Let me see if I can do the second option.

**Comment by mieschc** [comment]
Option 2 sounds great to me. Thank you for checking.
