### ISSUE TITLE
Entity sensor.panasonic_heat_pump_main_holiday_mode_state cannot be added as the entity category is set to config

### ISSUE THREAD

**Issue by sermayoral** [kamaradclimber/heishamon-homeassistant#163]
** Versions **

- Home Assistant version (for instance 2023.9): 2023.11.3
- This integration version (for instance 1.1.0): 1.4.1

> [!IMPORTANT]
> It's even better if you can make sure you are using the lastest version for the integration (https://github.com/kamaradclimber/heishamon-homeassistant/releases)

Any time i restart/reboot Home Assistant, I get the following error:

```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:507
Integration: Sensor (documentation, issues)
First occurred: 20:11:00 (1 occurrences)
Last logged: 20:11:00

Error adding entities for domain sensor with platform aquarea
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1021, in add_to_platform_finish
    await self.async_internal_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 279, in async_internal_added_to_hass
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity sensor.panasonic_heat_pump_main_holiday_mode_state cannot be added as the entity category is set to config

```

**To Reproduce**
1. Restart/Reboot the system
2. Show the log

**Expected behavior**

Not to have the error

**Screenshots**

** MQTT dump **

**Comment by kamaradclimber** [comment]
Thanks for the report, I can reproduce the issue with 2023.11.0 but not with 2023.10.3. I'll investigate what changed and fix it.

**Comment by kamaradclimber** [comment]
It comes from https://github.com/home-assistant/core/pull/103210 and https://github.com/home-assistant/core/pull/101471 which introduced a warning. I disagree with the interpretation of what "config" means but I don't think there is a point in opening a bug (especially given answers to https://github.com/home-assistant/core/pull/101471#issuecomment-1793684607).

I'll change the impacted entity categories to diagnostic and it should fix this ~warning~ error.

**Comment by sermayoral** [comment]
Thanks!
