### ISSUE TITLE
swapped names - Heat Curve

### ISSUE THREAD

**Issue by ttplayer** [kamaradclimber/heishamon-homeassistant#165]
** Versions **

- Home Assistant version (for instance 2023.9):    Home Assistant 2023.10.0
- This integration version (for instance 1.1.0):       1.4.2

Description

No big Deal, but "highest/lowest" target temperatures for the heating curve are reversed.

[Heat Curve.pdf](https://github.com/kamaradclimber/heishamon-homeassistant/files/13597391/Heat.Curve.pdf)

Best Regards
Axel

**Comment by kamaradclimber** [comment]
Hello,

thanks for the report, would you be interested in submitting a pull request to fix it?

**Comment by ttplayer** [comment]
No problem, if you explain me, what I've to do??

**Comment by kamaradclimber** [comment]
You have to look at [this part of the code](https://github.com/kamaradclimber/heishamon-homeassistant/blob/main/custom_components/aquarea/definitions.py#L626-L676) and see how it can be improved.

**Comment by ttplayer** [comment]
Ahh, now I understand. But, I've no clue of changing a programm-code and see only cryptic signs.
Sorry -(

**Comment by sorenfisker** [comment]
This was correct before but is now broken.
Please refer to the Heishamon documentation and roll this back.
https://github.com/Egyras/HeishaMon/blob/master/MQTT-Topics.md

**Comment by kamaradclimber** [comment]
https://github.com/kamaradclimber/heishamon-homeassistant/releases/tag/1.6.1 revert to previous behavior. As I wrote in the original PR, I found mqtt topics description very confusing: every time I look at it I understand in the wrong way.
Thanks for the report @sorenfisker

**Comment by sorenfisker** [comment]
@kamaradclimber
Totally agree - the naming is horrible and the mismatch between names and descriptions just makes it worse :-)

**Comment by geduxas** [comment]
Heh.. it can bee fixed in integration naming :) maybe there is one word missing.. 

Highest water target temperature **ON** lowest outdoor..

I simply using O_Hi, W_Lo  naming schema as used in seevice manual.

**Comment by Bucky2k** [comment]
I would actually prefer short names as in manual. The long ones are never visible on my mobile screen anyway

**Comment by geduxas** [comment]
@kamaradclimber i just noticed now that meaning go wrong, don't knows if it from this fix or no.. but i have set my config after first it release.. and everything was fine ;) now i suddenly notice that it went in opposite way 

![IMG_20240214_195208](https://github.com/kamaradclimber/heishamon-homeassistant/assets/18700450/c5867a8e-7608-4aba-bad3-51decdb01d17)
![Screenshot_2024-02-14-19-59-09-22_c3a231c25ed346e59462e84656a70e50](https://github.com/kamaradclimber/heishamon-homeassistant/assets/18700450/df9be269-be6c-450e-b3a4-b40c87f4cae6)

**Comment by ttplayer** [comment]
Hmm, no changes in my config.
high is high an low is low - maybe cause I tuned the descriptions in HA from early on......

**Comment by geduxas** [comment]
> Hmm, no changes in my config. high is high an low is low - maybe cause I tuned the descriptions in HA from early on......

it was ok before, now it's reverset,

TOP29 Target water temperature in lowest outside point, WaterHigh_OnLowOutside (negative outside, higher water temperature)
TOP30 is oposite (lowest water temperature point (in highest outside point) WaterLow_onHighOutside (Positive outside, lower water temperature)
TOP31 Outside highest point,
TOP32 Outside lowest point.

By latest change TOP29 which should mean highest water target temperature renamed fro HIGH to LOW,
TOP30 which sould mean lowest water target temperature renamed from LOW to HIGH

same for zone2..
