### ISSUE TITLE
Prepare Opentherm Topics

### ISSUE THREAD

**Issue by Binifada1956** [kamaradclimber/heishamon-homeassistant#166]
The latest Heishamon hardware has added Opentherm to the control system. 
Are there plans to include this in the integration?

**Comment by geduxas** [comment]
Could you share more details about it? What functionality is missing? And what you would like to do with opentherm?

**Comment by kamaradclimber** [comment]
Hello, thanks for opening an issue.

@Binifada1956 , I'm not familiar at all with opentherm, could you be more specific about what would you like to see in this integration about opentherm?

**Comment by kamaradclimber** [comment]
I'll close that issue but feel free to put a comment if there are any news
