### ISSUE TITLE
Incorrect Power Consumed and Produced readings

### ISSUE THREAD

**Issue by Toma82** [kamaradclimber/heishamon-homeassistant#168]
** Versions **

- Home Assistant version (for instance 2023.12.3)
- This integration version (for instance 1.4.2)

Panasonic J series

![image](https://github.com/kamaradclimber/heishamon-homeassistant/assets/81713401/ec905448-27a4-4e4f-a29e-11244fb98593)
I have been using the integration for a week and I noticed that the Power Consumed readings are incorrect, both for central heating and hot water, and the total does not match. For example, the daily one shows the following:
DHW 1,245 kWh
Heating 7.902 kWh
DHW + central heating 8.302 kWh The generated energy is also shown incorrectly
The biggest distortions seem to me to be in the DHW

**Comment by blendrik** [comment]
I kind of solved this issue with a dirty workaround:
 
 Read this: https://github.com/home-assistant/core/issues/88940
 
 And use this in between the sensors: https://github.com/dgomes/ha_sampler
 
 Maybe there is a chance, that this "sampler" could be integrated into heishamon-homeassistant. ;-)

**Comment by Toma82** [comment]
I'm also testing this solution now, we'll see what it will look like after a few days, I also have an external counter so there will be something to compare it with

**Comment by blendrik** [comment]
Good. Be sure not to set the sample rate too low. I chose 10 seconds. Otherwise it will result in a large states database.
I did this for production sensors, as well as for consumption sensors.


Am 29. Dezember 2023 15:58:11 MEZ schrieb Toma82 ***@***.***>:

**Comment by Toma82** [comment]
I'm currently testing this solution:

monthly_energy:
   source: sensor.panasonic_dhw_production
   name: monthly_production_panasonic_dhw
   cycle: monthly

sensor:
  - platform: integration
    source: sensor.panasonic_heat_pump_main_dhw_power_production
    name: "Panasonic DHW Production"
    method: left
    unit_prefix: k
    unit_time: h
    round: 2

**Comment by Bucky2k** [comment]
I am using this since already a year:

sensor:  #Calculation Energy consumed (kWh) - DHW
  - platform: integration
    source: sensor.panasonic_heat_pump_main_dhw_energy_consumption
    name: Aquarea DHW Energy Consumed
    round: 1
    unit_prefix: k
    method: left
  #Calculation Energy consumed (kWh) - Heat
  - platform: integration
    source: sensor.panasonic_heat_pump_main_heat_energy_consumption
    name: Aquarea Heat Energy Consumed
    round: 1
    unit_prefix: k
    method: left
  #Calculation Energy consumed (kWh) - Cool
  - platform: integration
    source: sensor.panasonic_heat_pump_main_cool_energy_consumption
    name: Aquarea Cool Energy Consumed
    round: 1
    unit_prefix: k
    method: left

**Comment by Bucky2k** [comment]
As I used my own riemann integrator for a year, I did not notice this update until today. Any guesses, why it is not showing anything?

![Screenshot_20231229_212638_Home Assistant](https://github.com/kamaradclimber/heishamon-homeassistant/assets/67497826/c36abbb4-19f1-41fc-acab-b106c61992dd)

**Comment by geduxas** [comment]
@Bucky2k it's depends on which heishamon firmware you're running, also which version of integration you have.. recently heishamon have changed it's mqtt value.

**Comment by Bucky2k** [comment]
> @Bucky2k it's depends on which heishamon firmware you're running, also which version of integration you have.. recently heishamon have changed it's mqtt value.

Sorry, I was not following here for a while and even missed, that you integrated the riemann integrals I proposed a while ago. 

I am running latest Heishamon 3.2.3 

I will need to spend some time cleaning and also to understand, if it is correct that my HA entities remain with "energy" rather than "power" in the naming of the sensors. I guess you kept the energy naming in HA on entity level?

**Comment by geduxas** [comment]
I think you should flush mqtt data.. it could help, and no you're confusing me with @kamaradclimber  :)

**Comment by Bucky2k** [comment]
Okay, forget my comments, back to topic - did a full delete & reinstall of the integration, now it's counting. Old entity names with energy in the naming were the most probable reason for the non-functioning counters.


No I can start oberserving if I also see a miscalculation as described in this thread

**Comment by kamaradclimber** [comment]
Hello all, thanks for the discussion.

@blendrik , I would be surprised the sampler trick would help because we are integrating "instant" values about power that are likely to change all the time (unless your heatpump works 100% of the time at max capacity).
The bug you point out may indeed affect the integration but I believe only on short period (a few hours maximum) because the heatpump energy consumption varies quite fast in my experience (it runs for an hour then stop or reduce rotation).

Do you see a different behavior?

**Comment by Toma82** [comment]
Hi ,
After the first day of observation he has the following data
With counter meter:
Heat 17.53
DHW 2.93
Heat+DHW 20.46
from calculations using Riemann:
Heat 17.47
DHW 3/01
Heat+DHW 20.48
With heishamon
Heat 16/01
DHW 11.86
Heat+DHW 17.61

Instead of that today
With counter meter:
Heat 13.41
DHW 1.4
Heat+DHW 14.81
from calculations using Riemann:
Heat 12.33
DHW 1.46
Heat+DHW 13.79
With heishamon
Heat 13.51
DHW 7.47
Heat+DHW 14.11

As you can see, the biggest distortions are on DHW

**Comment by blendrik** [comment]
@kamaradclimber, I think the problem is the way the riemann integration works. As stated in https://github.com/home-assistant/core/issues/88940 the riemann integration only updates on state change: "The current implementation is event driven to support sensors that update often (which is also when Riemann Sum best approaches the integral function)."

My DHW power production and consumption values where always too high. The normal heating values where ok, as long as the pump is runnning. When there are intervals where the consumption is 0 watts and then it starts again and e.g. 800 watts is consumed the riemann integration "adds" the gap with values that are not 0, but somehow calculated.

When I add the sampler in between, the state values are updated every 10 seconds (in my case) and than the riemann integration can calculate more precise.

So, what we need here, is a state update, even if the value is the same.
But that is more of a general problem in home assistant, rather than of this integration. The sampler is a good work around for this "problem", but it generates a lot of data and blows up my maria db.

I observed the same behavior with a crappy tuya power plug, which was only capable of showing watts and not kWh.

Another thought: Maybe we only need one state update of 0 watts BEFORE it goes up to any higher value. That way the database blow up could be avoided, because there no unessessary states in there. But I could be totally wrong ;-)

**Comment by Bucky2k** [comment]
> Hi , After the first day of observation he has the following data With counter meter: Heat 17.53 DHW 2.93 Heat+DHW 20.46 from calculations using Riemann: Heat 17.47 DHW 3.01 Heat+DHW 20.48 With heishamon Heat 16.01 DHW 11.86 Heat+DHW 17.61
> 
> Instead of that today With counter meter: Heat 13.41 DHW 1.4 Heat+DHW 14.81 from calculations using Riemann: Heat 12.33 DHW 1.46 Heat+DHW 13.79 With heishamon Heat 13.51 DHW 7.47 Heat+DHW 14.11
> 
> As you can see, the biggest distortions are on DHW

What do you mean exactly by

 "counter meter" --> calibrated heat meter?
"Calculations using riemann" --> integrate power consumption values from Heishamon integration
"Heishamon" --> ??? Same as above? Heishamon does not deliver kWh....

**Comment by Bucky2k** [comment]
First comparison "Heishamon integration" vs. heat meter:

![Screenshot_20231231_161810_Home Assistant](https://github.com/kamaradclimber/heishamon-homeassistant/assets/67497826/219b71ee-e2ca-48af-94ce-117084ba2bd6)

**Comment by Toma82** [comment]
"counter meter" --> calibrated heat meter?  **I meant the energy meter**
![image](https://github.com/kamaradclimber/heishamon-homeassistant/assets/81713401/aa31ef1d-2fb8-4090-99f2-452a4bfa5642)

"Calculations using riemann" --> integrate power consumption values from Heishamon integration 
**Yes, exactly, e.g sensor.panasonic_heat_pump_main_heat_power_consumption**
 " - platform: integration                                                                                                                                                         
    source: sensor.panasonic_heat_pump_main_heat_power_consumption                                                                                                                          
    name: "Panasonic heate"                                                                                                                                   
    method: left                                                                                                                                                                  
    unit_prefix: k                                                                                                                                                                
    unit_time: h                                                                                                                                                                  
    round: 2 "
"Heishamon" --> ??? Same as above? Heishamon does not deliver kWh....
I know that Heishamon himself does not provide kWh information, but the integration itself does
Based on these senosrows I made utility_meter . 
![image](https://github.com/kamaradclimber/heishamon-homeassistant/assets/81713401/b25bdb31-7a34-48a8-835f-1eace1c47e96)
![image](https://github.com/kamaradclimber/heishamon-homeassistant/assets/81713401/f97ee77d-2910-4005-83bc-d9dc2b1007cf)

**As you can see, they differ from Riemann, estimate the sensor integral**
![image](https://github.com/kamaradclimber/heishamon-homeassistant/assets/81713401/efcf6f80-9d60-49cd-83c4-b36c71b42d43)
![image](https://github.com/kamaradclimber/heishamon-homeassistant/assets/81713401/a50856b9-53a7-4761-bcc3-dce579c6545d)

**Comment by kamaradclimber** [comment]
> watts is consumed the riemann integration "adds" the gap with values that are not 0, but somehow calculated.
> 
I think this is linked to the choice of `trapezoidal` integration method, which uses [average values](https://github.com/home-assistant/core/blob/70e2ff351da38a72266966a2557ce80814966815/homeassistant/components/integration/sensor.py#L347-L349)


> Another thought: Maybe we only need one state update of 0 watts BEFORE it goes up to any higher value. That way the database blow up could be avoided, because there no unessessary states in there. But I could be totally wrong ;-)

I'll make an update to use method `left` which may be better (it should not hallucinate values and will work better for long period with 0 values). The downside is that values will not be good if HA stays down for some time when energy measurement is not 0 (but no easy solution will work for that case)

**Comment by kamaradclimber** [comment]
@Toma82 could you retry with https://github.com/kamaradclimber/heishamon-homeassistant/releases/tag/1.4.3 and tell me if the situation improves?

**Comment by Bucky2k** [comment]
> > watts is consumed the riemann integration "adds" the gap with values that are not 0, but somehow calculated.
> 
> I think this is linked to the choice of `trapezoidal` integration method, which uses [average values](https://github.com/home-assistant/core/blob/70e2ff351da38a72266966a2557ce80814966815/homeassistant/components/integration/sensor.py#L347-L349)
> 
> > Another thought: Maybe we only need one state update of 0 watts BEFORE it goes up to any higher value. That way the database blow up could be avoided, because there no unessessary states in there. But I could be totally wrong ;-)
> 
> I'll make an update to use method `left` which may be better (it should not hallucinate values and will work better for long period with 0 values). The downside is that values will not be good if HA stays down for some time when energy measurement is not 0 (but no easy solution will work for that case)

I always used "left", maybe that's why I never noticed big deviations

**Comment by Toma82** [comment]
> @Toma82 could you retry with https://github.com/kamaradclimber/heishamon-homeassistant/releases/tag/1.4.3 and tell me if the situation improves?

I update to version 1.4.3
I'll let you know what it looks like tomorrow, but the LEFT method is definitely better and shows relatively similar values ​​to the original energy meter

Happy New Year 2024 :)

**Comment by Toma82** [comment]
@kamaradclimber Thanks for the change, now everything works properly. Topic to be closed,You did a very good job.

**Comment by kamaradclimber** [comment]
Glad to hear this, thanks all for your inputs!
