### ISSUE TITLE
Handles to switch between compensation curve and direct 

### ISSUE THREAD

**Issue by taugusti** [kamaradclimber/heishamon-homeassistant#180]
**Is your feature request related to a problem? No - an optimization**

I use Heishamon to control the floor heating and hot water in my summerhouse via home assistant and the hass plugin.
it all works like a bliss!

I have a "vacation mode" setting that changes the setpoint and mode of the heatpump.

I would like to reduce the on/off cycles in non-vacation mode. I would like to do this by opening all floor heating circuits and control the temperature by setting the direct heat setting.

For this purpose, I would like to change from compensation curve to direct heat. 
I have found a sensor that reflects the current configuration - but not a setting to change it:
TOP76 | main/Heating_Mode | Compensation / Direct mode for heat (0 = compensation curve, 1 = direct)

**Describe the solution you'd like**
So - the feature request is to add the ability to change the mode between direct heat and compensation curve control.

**Describe alternatives you've considered**
Changing it from the display - but  that is not really an option :-)

**Additional context**
Nothing I can think of :)

**Comment by kamaradclimber** [comment]
Hello,

I think you should request this feature first on the upstream project: https://github.com/Egyras/HeishaMon.
This integration is _just_ the glue between heishamon and home-assistant.

**Comment by taugusti** [comment]
Of cause - I mised up the projects'
Thanks!
