### ISSUE TITLE
Zone 1/2 Heat Requested Shift limits are out of range

### ISSUE THREAD

**Issue by thekeymeister** [kamaradclimber/heishamon-homeassistant#183]
** Versions **

- Home Assistant version (for instance 2023.9): 2024.1.2
- This integration version (for instance 1.1.0): 1.5.1
- Heat pump (if it matters): WH-MXC09J3E5 9 1ph T-CAP
- HeishaMon version: 3.2.3

**Describe the bug**

I am using "Zone 1 Heat Requested Shift" (number.panasonic_heat_pump_main_z1_heat_request_temp) to control the house heating temperature, this has worked fine for months.  Unfortunately after upgrading from 1.4.6 to 1.5.1 the lower limit of both Zone 1 & 2 Heat Requested Shift seems to be 20*C.  This is not ideal as I used to run it at 18*C and my house has become too hot!

Rolling back to version 1.4.6 seems to fix this, albeit the maximum value is then 20*C. I rolled back a version at a time and can confirm the issue starts with version 1.4.7.

I know I should really be using the climate entity (climate.panasonic_heat_pump_main_z1_temp) for this, but this has never worked for me either.  Pressing the + or - to change the temperature just results in it trying to set it to 5*C no matter what the current temperature set point is.  It then just reverts back to what it was before.  Using "Zone 1/2 Heat Requested Shift" worked fine for me previously.  Not sure if this is just me or a wider issue as it's always been like that - I'm more than happy to try and provide any more info around the climate entity not working if required.

**To Reproduce**
1. Go to Integrations and find the Heat Pump indoor unit
2. Scroll down to 'Configuration' and find 'Aquarea Zone 1 Heat Requested Shift'
3. Try and set it to anything below 20*c

**Expected behavior**

Allowable Zone 1/2 temperature range between 10*-30*C. I have confirmed this is the range the Panasonic indoor controller allows - on my unit at least

**Comment by thekeymeister** [comment]
It looks like it's related to this pull request
https://github.com/kamaradclimber/heishamon-homeassistant/pull/170

I think something has gone wrong there as the Heat Requested Shift is being used for the flow temperature in whatever mode is being used there, so the main/max values are correct in 1.4.7 onwards. In the mode I am using, Heat Requested Shift is for room temperature so definitely doesn't want to be 20-60*C.

**Comment by geduxas** [comment]
i think it soon will be fixed, Panasonic have couple of heating options with it's own temperature ranges.. so it's need to implement some changes (#167) .. after that i think it will be possible to better control thermostat.

**Comment by kamaradclimber** [comment]
Sorry for the bug and its impact. It's hopefully fixed in 1.5.2 of this integration
