### ISSUE TITLE
Water temperature in zones

### ISSUE THREAD

**Issue by meavric** [kamaradclimber/heishamon-homeassistant#185]
Hi, i use two zones. If I change to 1 zone in 2 zone I get on sensor 
sensor.panasonic_heat_pump_main_z2_water_temp temperature -128 C.
I thing this temperature be set to 0.

I use last version HA and heishamon

Br

**Comment by PGnl** [comment]
This is not a fault of the integration.
This is a direct readout of the Heishamon (all integrations like home assistant, domoticz and others will give this response)
-128, I just read as zone is OFF.

**Comment by kamaradclimber** [comment]
Hello, thanks for the report.

I'm not sure I understand the exact scenario "f I change to 1 zone in 2 zone ".
Here is a proposal https://github.com/kamaradclimber/heishamon-homeassistant/pull/188/files, let me know if that would solve your issues.

**Comment by meavric** [comment]
Yes, it is good solution for me, if value is -128 then none

**Comment by artlov** [comment]
I'm not sure do I understood this patch correctly, but if I temporarily switched off Zone2 then temperature graphs ("Aquarea Zone 2 climate current temperature" and "Aquarea Zone 2 climate heating") messed with -128. Maybe it would be good to replace -128 with 0 in this situation? 
Version 1.7.0
![image](https://github.com/kamaradclimber/heishamon-homeassistant/assets/6746304/e22fe04d-1c64-4633-8b5d-7a2f8586b1bb)
