### ISSUE TITLE
Unable to set target temperature when using "Room Thermostat (Internal) - Weather Compensation" despite this being applicable in this mode

### ISSUE THREAD

**Issue by teun95** [kamaradclimber/heishamon-homeassistant#190]
**Versions**
- Home Assistant version: 2024.1.3
- This integration version: 1.6.1

**Describe the bug**
My heat pump uses a compensation curve and uses the main remote control unit as thermostat (called "Room Thermostat (Internal) - Weather Compensation" in the manual). 

The climate entity is displayed correctly, but the target cannot be changed from the thermostat card. This is because the climate entity has as attributes `min_temp: -5` and `max_temp: 5`. Strangely enough, using `climate.set_temperature` the temperature can be set directly. 

The attributes of  `climate.panasonic_heat_pump_main_z1_temp`
```
hvac_modes: heat, off 
min_temp: -5 max_temp: 5 
target_temp_step: 1 
current_temperature: 18 
temperature: 19 
friendly_name: Aquarea Zone 1 climate 
supported_features: 1
```

**To Reproduce**
1. Switch heat pump to "Room Thermostat (Internal) - Weather Compensation"
2. Attempt to increase or decrease the room thermostat target using the dashboard card

**Expected behavior**

I would expect to be able to change the target temperature of the room thermostat using the thermostat card as this the use of `climate.set_temperature` demonstrates that this is functional in my setup.

**Screenshots**
* [Description of my setup as described in the manual](https://github.com/kamaradclimber/heishamon-homeassistant/assets/37039643/257b07f3-30ed-4b8f-9036-1b06bd3e85a1)
* [Thermostat card is displayed correctly](https://github.com/kamaradclimber/heishamon-homeassistant/assets/37039643/a957f8b1-ac13-43d9-9c0c-c63276e492bd)
* [After pressing + to increase the temperature with 1 degree](https://github.com/kamaradclimber/heishamon-homeassistant/assets/37039643/5a06fb96-e1c4-4c71-9a0c-67a3d7aed765)

**Comment by teun95** [comment]
A similar behavior was mentioned in a comment [here](https://github.com/kamaradclimber/heishamon-homeassistant/issues/34#issuecomment-1762957181) by @archi, but the configuration described contained many more variables than my setup.  Consequently the discussion might have focused on the emulation of the optional PCB, while this was unrelated to the cause. The setup in this issue does not use the optional PCB. I decided to open a new issue as the comment was not the same as the one described in the issue.

**Comment by kamaradclimber** [comment]
Hello, thanks for the clear report!
I think https://github.com/kamaradclimber/heishamon-homeassistant/pull/167/files is in the right direction to fix the issue you encounter.
Could you have a look and confirm? (the PR is not ready yet but close)

**Comment by teun95** [comment]
I don't have the knowledge to evaluate whether the changes in the PR make sense, but I have changed my climate.py in HA to the one in the PR and the climate card and I can confirm that this fixes the issue. The climate card is now behaving as expected. Thanks for the work!

**Comment by kamaradclimber** [comment]
I've put https://github.com/kamaradclimber/heishamon-homeassistant/releases/tag/1.7.0 in pre-release so you can install it with hacs (you need to accept "beta" releases). Don't hesitate to give more feedback!

**Comment by teun95** [comment]
I have this (1.7.0 from HACS) running on two Home Assistant instances now with different heat pumps and I haven't run into any issues so far. Thanks for the fix! I think this issue can be closed.
