### ISSUE TITLE
mqtt variable closed loop

### ISSUE THREAD

**Issue by KalleArulaane** [kamaradclimber/heishamon-homeassistant#200]
Hello,

there seems to be a bug in writing values to Heishamon over MQTT.

For variables that can be written to the heat pump there are input numbers and sensors both.
The only correct way to read / write variables to a remote system that is not guaranteed to accept the values at least not any guaranteed timeslot is to transmit it and then read back if the change has been successful. This is true for all non-real-time systems and even for really controlled environments it is the suggested way to do things.
However, it seems that the input_number value gets sent over MQTT and then the input number itself (sic!) is assigned the read back value. If timings are bad then you will have echoes (I had).

I fixed this by removing the code for all input numbers being read back from mqtt (one snippet shown, others behave the same way). Please note that all works nicely without this code.

```
###########################
#Fetches tank target temperature from status and sets the selector accordingly

alias: Set tank target temperature selector
trigger:
platform: mqtt
topic: “panasonic_heat_pump/main/DHW_Target_Temp”
action:
service: input_number.set_value
data_template:
entity_id: input_number.heishamon_tank_temp
value: >-
{{ “%.1f” % (trigger.payload | int) }}


##############################

```

Thanks,
Kalle

**Comment by geduxas** [comment]
To be clear, are you referring to heishamon with direct configuration or this project?

**Comment by KalleArulaane** [comment]
TOP76 = 0 - compensation curve.

**Comment by kamaradclimber** [comment]
@KalleArulaane thanks for reporting this.
As geduxas suggested, I think you are using the yaml configuration from https://github.com/Egyras/HeishaMon/blob/master/Integrations/Home%20Assistant/heishamon.yaml#L267-L276 which is different from this integration. Am I correct?

It’s of course possible that this integration (the one defined in the current repository) suffers from the same issue. I remember having faced echoes in the past.

Let me know if you can reproduce using this one.

**Comment by KalleArulaane** [comment]
omg, i feel stupid. yes, i am posting under a wrong project. sorry for the confusion! :D
