### ISSUE TITLE
I am on an alpha Heishamon version and get nagged for a downgrade...

### ISSUE THREAD

**Issue by stumbaumr** [kamaradclimber/heishamon-homeassistant#201]
Currently I am running an alpha version and are asked by home assistant to make a downgrade...
![grafik](https://github.com/kamaradclimber/heishamon-homeassistant/assets/12425441/f513eeee-79f0-4a1d-83e7-4225017b0d40)

**Versions**

- Home Assistant version 2024.4.4
- This integration version 1.7.3

**Describe the bug**

Currently I am running an alpha version and are asked by home assistant to make a downgrade...

**To Reproduce**
1. Install alpha from https://github.com/IgorYbema/HeishaMon/actions
2. Configure
3. See update recommendation in Home assistant settings

**Expected behavior**

Filter out alphas as being newer than current version

**Comment by kamaradclimber** [comment]
Thanks for reporting this.

This is an interesting case!

We could indeed filter out alpha release but it means you could be on an 3 years old alpha and not get the update info.

The alternative would be have heishamon use a more conventional version format for alphas. I think `3.2.4-alpha-xxx` would be properly considered by the home-assistant update component (as higher than 3.2.3 but lower than a 3.2.4).

I'll make a small patch to ignore versions that starts with alpha and ping @Egyras and @IgorYbema see if they want to change the versioning.

**Comment by kamaradclimber** [comment]
https://github.com/kamaradclimber/heishamon-homeassistant/releases/tag/1.7.4 is in pre-release, you can test it and let me know if it fixes the issue.

**Comment by geduxas** [comment]
Alpha builds will always be to test system, or even self build version.. so don't know if there is any point to track alpha builds.. just ignore
