### ISSUE TITLE
Add state_class for 1wire sensors

### ISSUE THREAD

**Issue by Vallatu** [kamaradclimber/heishamon-homeassistant#206]
**Is your feature request related to a problem? Please describe.**
I have five 1wire temperature sensors connected to Heishamon and I would like to utilize Home Assistant's long term statistics for them, however, since these sensors in HA don't have `state_class` attribute defined, they are not included in the long term statistics. 

**Describe the solution you'd like**
Add `state_class: measurement` attribute to 1wire sensors

**Describe alternatives you've considered**
Using `customize.yaml` (as described [here](https://community.home-assistant.io/t/benefit-from-long-term-statistics-for-any-sensor/338076)) but I believe this is a feature that would benefit lots of people and I would prefer not to add separate customizations where possible (easier to manage HA instance).

**Additional context**
[Documentation](https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics)
Similar to https://github.com/Egyras/HeishaMon/pull/292

**Comment by kamaradclimber** [comment]
https://github.com/kamaradclimber/heishamon-homeassistant/releases/tag/1.7.6 contains the patch
