### ISSUE TITLE
Water pressure sensor (TOP115) missing?

### ISSUE THREAD

**Issue by b3nn0** [kamaradclimber/heishamon-homeassistant#208]
**Is your feature request related to a problem? Please describe.**
Hi,
for some reason, the Water_Pressure MQTT topic seems to be missing from this integration. I can see it in MQTT Explorer, but not in HA. Would it be possible to add this?
![image](https://github.com/kamaradclimber/heishamon-homeassistant/assets/1858945/ad153284-4e75-49c4-9188-fad8e4f4851a)

**Describe the solution you'd like**
Add a water pressure sensor to HA

**Describe alternatives you've considered**
If there is good reason why this doesn't exist yet, let me know, then I'll do it via MQTT sensors, but it feels like this was just forgotten?

**Additional context**
Not sure if all Aquareas have this sensor, but at least my L series does.

Anyway, thanks a lot for your work! Makes integration of Heishamon a breeze.

**Comment by kamaradclimber** [comment]
https://github.com/kamaradclimber/heishamon-homeassistant/releases/tag/1.8.0 should bring compatibility with 3.2.4-beta-2 . Thanks for the report!
