### ISSUE TITLE
Adding of COP calcs based on S0 on heisha and Dallas sensors

### ISSUE THREAD

**Issue by PGnl** [kamaradclimber/heishamon-homeassistant#22]
Let me start by saying thank you for the excellent work.
All the official pana sensors work along with some heisha data (for example MQTT connections and uptime etc..)

The following would also be great.
If S0 measurements come in.
Add sensor for S0 (2 times when available) 
Or just add and hide.

When Dallas sensor are available in MQTT in standard pana. Add these as temp sensors based on Dallas ID.

I am a complete newby in HA, so can offer limited support myself.

Typical topic Dallas sensor:
topic: `panasonic_heat_pump/1wire/286c3802422001fc`
message: `14.62` (in degrees)
where 286c3802422001fc is a specific identifier of my dallas and will vary based on the sensor.
I currently have 5 dallas sensors, but some have more (or less sensor)
So that would mean adding each line that is found as a temp sensor based on its name

Typical S0 (3 topics with 1 being main and 2 being backup heater)
panasonic_heat_pump/s0/Watthour/1                      current message 0.50
panasonic_heat_pump/s0/Watthour/2                      current message 0.00
panasonic_heat_pump/s0/WatthourTotal/1              current message 27.00
panasonic_heat_pump/s0/WatthourTotal/2              current message 0.00
panasonic_heat_pump/s0/Watt/1                             current message 9.00
panasonic_heat_pump/s0/Watt/2                             current message 0.00

COP calculation would be added if S0 is available based on produced energy divided by sum of S0 sensors.
equal to the standard heisha yaml.
[https://github.com/Egyras/HeishaMon/blob/master/Integrations/Home%20Assistant/heishamon.yaml](url)
line 611 onwards.

Again.. love the work you did. 
Used it now (today) remotely for someone that stepped over from Domoticz.

**Comment by kamaradclimber** [comment]
Thanks for your feedback.
If the mqtt topic depends on sensor id, I am not sure it will be easy to detect it and create a sensor based on it.
I would recommend in a first step to create the mqtt sensor manually (you can do it in `configuration.yaml`).
I can have a look but since I don't have this setup at home, I can't guarantee I'll be able to provide a functional system.

**Comment by PGnl** [comment]
I currently have them added via yaml. That is not the issue. It would just be so easy 😉
I like your method much more. Also to help others. Was able to explain someone (with no experience in HA) to set up heisha via the phone today using your add on

**Comment by PGnl** [comment]
I am more than happy to sponsor you some dallas sensors ;)
Just let me know how I can help.

**Comment by geduxas** [comment]
@PGnl but you are missing key element for heat energy calculation.. flow sensor.. if you don't trust temperature sensors, why flow sensor is exception?

**Comment by kamaradclimber** [comment]
Here is what I propose as a first step: add sensors for detected 1wire (dallas) and S0 sensors.

Could you clarify what the two S0 sensors are plugged to? What are they measuring exactly?

**Comment by geduxas** [comment]
Those are usually connected to external energy meter, heishamon board have ability to connect to 2 energy meters, to get impulses about energy usage. By mqtt HA integration usually S0 port will be for heatpump energy consumption, and S1 port for backup heaters..

**Comment by PGnl** [comment]
Mine are mostly measuring in and outlet temperatures. These are more exact and measure at two decimals behind the comma.
The flow is always high when pumping. The error is relatively constant.
Often, the Dallas sensor measurement are combined with the pana flow for COP calcs . This gives quite accurate measurements.  
I also have one Dallas for outside temperature and one for floor water temperature and one for “in cabinet” measure the. 
but people use it in various ways.

**Comment by PGnl** [comment]
Note S0 and S1 are always named the same, for everyone. Only Dallas (1 wire) vary

**Comment by geduxas** [comment]
> Mine are mostly measuring in and outlet temperatures. These are more exact and measure at two decimals behind the comma. The flow is always high when pumping. The error is relatively constant. Often, the Dallas sensor measurement are combined with the pana flow for COP calcs . This gives quite accurate measurements. I also have one Dallas for outside temperature and one for floor water temperature and one for “in cabinet” measure the. but people use it in various ways.

Ok, i have pana with 2 zones, so 2 zones pumps are driven directly from panasonic. Also it's included in total energy calculation.. so why and how thous pumps should be eliminated or calculated in energy efficient calculation. This specified COP will also be way from accuracy. If you really would like to calculate COP, you should also measure power to compressor. And from that you should calculate it.  Also best way would be add heating energy meter. 

I wouldn't bother with inaccurate dallas sensors, inaccurate flow sensor, and inaccurate energy meter to calculate something what don't make any sense.

**Comment by kamaradclimber** [comment]
Release 0.6.2 has detection of S0 and 1wire sensors. It should be a good start already.

@PGnl do you think that would be enough to help you compute COP values that make sense for you?
If that's the case, let's close this issue. Otherwise, I'll probably need some time to understand the most common heatpump setup (mine seems to allow to compute COP without additional sensors).

**Comment by PGnl** [comment]
Magic.
all 1-wire sensors show up showing the correct values.
S0 1 and 2 show up
Watt works.
Watthour and WatthourTotal do not seem to work.
But could also be, because the heatpump is not heating ;)
So nothing to measure.
Brilliant work. first time I have my Dallas's show up automagically :)

**Comment by kamaradclimber** [comment]
Thanks for the report, I fixed this in 0.6.3, there was a small typo

**Comment by PGnl** [comment]
Now works great indeed. 
seems complete now. Only thing I have in yaml now is the climate entities for the 2 zones.

Perfect. Thank you very much.

would buy you a coffee, but no donate button on your site 😉
