### ISSUE TITLE
broken thermostat entity in heat mode when use direct mode.

### ISSUE THREAD

**Issue by kamaradclimber** [kamaradclimber/heishamon-homeassistant#220]
This patch broken thermostat entity in heat mode when use direct mode.
Before this update I can set water temperature in thermostat (i.g. 34°C) but after update range is -5 - +5 °C and it doesn't affect anything.

_Originally posted by @tjani8 in https://github.com/kamaradclimber/heishamon-homeassistant/issues/215#issuecomment-2189193590_

**Comment by kamaradclimber** [comment]
@tjani8 would you be able to confirm you have the issue in https://github.com/kamaradclimber/heishamon-homeassistant/releases/tag/1.9.1 and not in https://github.com/kamaradclimber/heishamon-homeassistant/releases/tag/1.8.0 ?

**Comment by tjani8** [comment]
Yes, problem come in 1.9.0 version and is still 1.9.1. I downgraded back to
1.8.0.

pe 28. kesäk. 2024 klo 9.33 Grégoire Seux ***@***.***>
kirjoitti:

**Comment by kamaradclimber** [comment]
My current assumption is that there is a bad interaction between the "cooling" and "heating" mode topics and the integration code is currently unable to distinguish those.

Could you give me the current value of the following mqtt topics:
-  .../main/Heating_Mode
- .../Main/Cooling_Mode
- .../main/Z1_Sensor_Settings
-  .../main/Z2_Sensor_Settings
-  .../main/Z1_Heat_Request_Temp
-  .../main/Z2_Heat_Request_Temp
- .../main/Operating_Mode_State
(where ... is the prefix used by your heishamon, probably something like "heishamon").

**Comment by tjani8** [comment]
Heating_Mode=1
Cooling_Mode=0
Z1_Sensor_Settings=0
Z2_Sensor_Settings=0
Z1_Heat_Request_Temp=32
Z2_Heat_Request_Temp=35
Operating_Mode_State=0

I use only zone 1 and cool mode is disabled via custom menu.

**Comment by kamaradclimber** [comment]
Thanks!
If you can try the current code in main branch  (commit 3101b9172cbe7d8a20fdc36cde666631644b0539) I think it can help with your issue.

**Comment by tjani8** [comment]
I now had time to test main branch code and I don't see any difference in functionality. Still have wrong adjust range in thermostat.

**Comment by kamaradclimber** [comment]
https://github.com/kamaradclimber/heishamon-homeassistant/releases/tag/1.10.0 should revert completely the broken feature.

**Comment by Rwatson111** [comment]
For me the cooling mode was there before the update, but it isn’t there anymore 
![IMG_0548](https://github.com/user-attachments/assets/bd102eeb-dc8f-4f52-9e3f-7aa2cfdb6f76)

**Comment by Rwatson111** [comment]
Seems tor me that in the initial post the issue may have not be related to the integration, but the setting of the heat pump itself. When you change the cooling function to cooling curve, the adjustment is between -5 and 5 degrees trim the calculated value based on the external temperature. Probably the same goes with the room controller. When you change to constant value you can actually operate on the water output temperature

**Comment by Rwatson111** [comment]
The +/- 5 values are ok, depending on the setting you have on the heat pump. It works the same for smart cloud
![IMG_0549](https://github.com/user-attachments/assets/a23a4863-3fb9-40e3-a57b-77a9566e445d)

**Comment by geduxas** [comment]
It's depends to heating/cooling mode.. if it's in compensation curve, then it will be -5/0/+5 range, if it in direct mode then it shoul allow full range of setpoint.

**Comment by Rwatson111** [comment]
Exactly, it worked yesterday before the update, now it doesn’t work anymore

**Comment by kamaradclimber** [comment]
Yes indeed, I’ve revert the support for cooling mode in climate entities in 1.10.0. It was breaking the heating behavior for other users and does not seem trivial to fix.
This feature is much harder for me to test because my heatpump does not have cooling mode so I cannot test on my setup.

Overall the multiplication of possible setup (compensation mode vs direct, heating vs cooling, various ways of getting temporature) makes developement of such feature harder.

If you want to help, you could send me a complete dump of mqtt messages so I can try to reproduce in a dev environment.

**Comment by Rwatson111** [comment]
The thing is I’m beginner in this. If you can tell me how  to do it step by step, I can do it

**Comment by Rwatson111** [comment]
The cooling can be turned on from custom menu. 
![image](https://github.com/user-attachments/assets/b9330a22-8b3d-4687-a7bb-7387342061ae)

**Comment by kamaradclimber** [comment]
If you have mosquitto, you can use:
```
mosquitto_sub -t panasonic_heat_pump/#  -u "$USER" -P "$PASSWORD" -h $HOST -v
```

It will dump all messages and you can send that to me. I don't think it would contain sensitive info but you should make sure. (in case of doubt, you can send them to me by email to heishamon_issue220@familleseux.net).

**Comment by geduxas** [comment]
@kamaradclimber i think it's better to separate thermostats.. truly personally i don't use -5/+5 shift thermostat at all.. don't see any use for it..
I would like it in auotomated way. Thermostat should set desired room temperature.

**Comment by kamaradclimber** [comment]
@geduxas you are probably right (as often!). I can try to work on this.

About always display target temperature, I would surely welcome a patch (or at least the formula to convert between -5/+5 delta to target temperature).

**Comment by geduxas** [comment]
It's simple.. just let it pick external temperature sensor for input, and by desired temperature tweak +5/-5 range.. if its in right spot then shift should be at 0, if it's to hot by +1° so it should set for example -2 shift value.. if it's to hot by +3° from setpoint, it should switch -5 shift... And don't know.. by some PID logic it should stear room temperature.. :)

**Comment by Bucky2k** [comment]
Not sure to follow. Most floor heating installations use no internal room sensor. So there is no room target temperature. There is only the heat curve water temperature defined and the thermostat adjusts with correcting the setpoint temp by -5 to +5°C....

**Comment by Rwatson111** [comment]
> Not sure to follow. Most floor heating installations use no internal room sensor. So there is no room target temperature. There is only the heat curve water temperature defined and the thermostat adjusts with correcting the setpoint temp by -5 to +5°C....

This is how I have it set up. Depending on the outside temperature, the zone output water temperature is adjusted.

l’ve sent my mqtt messages on email

**Comment by clandmeter** [comment]
> @kamaradclimber i think it's better to separate thermostats.. truly personally i don't use -5/+5 shift thermostat at all.. don't see any use for it.. I would like it in auotomated way. Thermostat should set desired room temperature.

I disagree and would prefer to be able to adjust the compensation curve temperature by +/- 5 Deg.
This is how my wife has used it since the beginning with the official implementation.

It also makes sense to mimic the behaviour of the indoor control panel also when running compensation curve.

If needed I can provide debug information.

**Comment by clandmeter** [comment]
@kamaradclimber I'm not sure this information is useful, but when switching from heat to cool compensation mode the wrong mqtt topic is used:

TOP27	Z1_Heat_Request_Temp
TOP28	Z1_Cool_Request_Temp

in Cool mode it should read and update TOP28 instead of TOP27

**Comment by geduxas** [comment]
Ok, but for shift value, thermostate component needed? Maybe slider is enough?
As for room temperature control you don't need to have separate room termostat.. only temperature sensor.. and in home assistant i think 90% will have one or another room temperature sensor ;)

**Comment by clandmeter** [comment]
From an UI pov, it is nice to have one component that can manage all of the modes adapting to each of them.
But as @kamaradclimber pointed out, it could be challenging to add this without having the mode available.

In any case, its my preference, and if needed I am able to help where needed.

**Comment by geduxas** [comment]
It's limited by HA itself.. i think it would be possible to implement with custom thermostat component..

**Comment by kamaradclimber** [comment]
https://github.com/kamaradclimber/heishamon-homeassistant/releases/tag/1.11.0 implements a separated climate component for cooling. Please open new issues if there are things to fix.
