### ISSUE TITLE
Integration/Energy Sensors suddenly gone

### ISSUE THREAD

**Issue by b3nn0** [kamaradclimber/heishamon-homeassistant#222]
** Versions **

- Home Assistant version (for instance 2023.9): 2024.07
- This integration version (for instance 1.1.0): 1.9.1

**Describe the bug**
Hi,
I just noticed that all the total-energy sensors have suddenly become unavailable, and HA's statistics repair tool says their unit changed from kWh to ''.
During startup, I can see this message in the log, which seems to be the reason for this. I think this was caused by the HA 2024.07 update.
```
2024-07-05 08:25:36.191 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up aquarea platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/aquarea/sensor.py", line 188, in async_setup_entry
    integration_sensors.append(EnergyIntegrationEntity(
                               ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: IntegrationSensor.__init__() missing 1 required keyword-only argument: 'max_sub_interval'
```

**Screenshots**
Sorry, renamed the entities a bit, it's just the ones created by the integration.
![image](https://github.com/kamaradclimber/heishamon-homeassistant/assets/1858945/4b155100-847e-4305-a281-efcc4c01ae6f)

See also:
https://github.com/nathanmarlor/foxess_modbus/discussions/635
https://github.com/home-assistant/core/pull/110685

**Comment by kamaradclimber** [comment]
Good catch, thanks for the report. It affects only HA 2024.7 and I've fixed this in 1.9.2

**Comment by wltng** [comment]
Thanks for the fix.
Although I am running HA 2024.7.0, trying to update results in an error stating my HA version is incompatible.

**Comment by b3nn0** [comment]
Looks like a bit of an unfortunate string comparison mismatch..
```
