### ISSUE TITLE
HACS does not show new version of this integration (was: Missing water pressure entity)

### ISSUE THREAD

**Issue by klausj1** [kamaradclimber/heishamon-homeassistant#226]
**Versions**

- Home Assistant version 2024.4.3
- This integration version 1.7.6

Heatpump: Leisha (L series)

**Bug description**

I cannot find the entity for water_pressure.

After some research I found out that it was added lately to this repo, and my version is too old. But HACS does not show me that there is a new version available:

![image](https://github.com/user-attachments/assets/cb83c9d6-0206-4573-a521-aef13265fd4a)

![image](https://github.com/user-attachments/assets/ffebc58a-1557-4c72-9fed-5a48fb8f53b6)

**To Reproduce**

On my side, just look into the HACS-pages.

**Expected behavior**

There should be a hint that an update is available.

**Question**

How can I update without loosing my settings? (I assume uninstall and installing again would work, but I am not sure).

**Comment by kamaradclimber** [comment]
Hello,

starting with https://github.com/kamaradclimber/heishamon-homeassistant/releases/tag/1.9.2, HA 2024.7 is required. I think this explains why no update is proposed to you.

I think you should be offered the ability to upgrade to 1.8.0 anyway but I don't know why it does not happen.
Have you tried to select a specific version?

![image](https://github.com/user-attachments/assets/ba69d435-3172-4e53-8534-b008c26d25ec)
![image](https://github.com/user-attachments/assets/810cd879-8af2-4a5f-bbd0-88709fb8729d)

You need at least https://github.com/kamaradclimber/heishamon-homeassistant/releases/tag/1.8.0 to get access to TOP115 measure (water pressure).

**Comment by klausj1** [comment]
Thanks, I updated HA, and now I see the update:
![image](https://github.com/user-attachments/assets/ffd53ce1-c096-43b2-9319-97b0f17e628f)

After the update the sensor is there:
![image](https://github.com/user-attachments/assets/d0c8bda4-b8c6-4624-81dc-fc19f4d1a95d)
