### ISSUE TITLE
Option to control the relays on large pcb

### ISSUE THREAD

**Issue by Rwatson111** [kamaradclimber/heishamon-homeassistant#227]
**Is your feature request related to a problem? Please describe.**
Cannot control the relays on large Heishamon PCB

**Comment by kamaradclimber** [comment]
Hello, 

I think the issue should be opened on https://github.com/Egyras/HeishaMon instead of this repository which focuses on the Home Assistant Integration.

I would also advise to add more details when opening the issue.

**Comment by Rwatson111** [comment]
I was redirected already, quote:

The relay function is not yet available in the home assistant integration.
The person how created that software needs to add that.

Can you check if the relay option is available in the integration before
removing my request?

Thanks in advance!

W dniu wt., 16.07.2024 o 13:06 Grégoire Seux ***@***.***>
napisał(a):

**Comment by kamaradclimber** [comment]
Ok thanks for the quote.
Could you give more details/documentation on what are the relays you refer to  please?
At the moment I can’t find details on Heishamon repository.

**Comment by IgorYbema** [comment]
Controlling the relays on the new large model isn't documented yet, however it is working.
It requires a mqtt publish on the topic panasonic_heat_pump/gpio/relay/one or panasonic_heat_pump/gpio/relay/two with a value of 0 or 1.

**Comment by kamaradclimber** [comment]
I would prefer to implement only features that are documented, it makes it easier to know when features are available for use.

**Comment by IgorYbema** [comment]
I'll update the documentation soon ;-)

**Comment by geduxas** [comment]
> I would prefer to implement only features that are documented, it makes it easier to know when features are available for use.

@kamaradclimber by in safe side, @IgorYbema is main hardware and software developer :) new boards are really fresh ones.. 

Your doing great job :) this integration becomes more and more important to heishamon community :)

**Comment by IgorYbema** [comment]
Documented now :) https://github.com/IgorYbema/HeishaMon/tree/main?tab=readme-ov-file#large-board-relay-control

**Comment by Rwatson111** [comment]
The relays works, thank you 😀
