### ISSUE TITLE
Set cool temp

### ISSUE THREAD

**Issue by guillermohor** [kamaradclimber/heishamon-homeassistant#230]
👋 Hello, thanks for you work

At parameter Z1_Cool_Request_Temp using direct. 
In order to set the cool temperature I use the parameter Z1_Cool_Request_Temp.
For that in file definitions line 441 I have to change the max to 26. With this change I can set ten cool temperature at home to 25 and it works perfect. native_max_value=25.
On line 447 : range(5, 26),
Line 449 true

**Comment by kamaradclimber** [comment]
Hello @guillermohor ,

thanks for the report. I've changed the ranges as you suggested.

I'll let `entity_registry_enabled_default=False`. It's used to hide by default all settings related to less common parameters (cooling for instance) to avoid overloading the interface.
I think you can enable them from the interface.

![image](https://github.com/user-attachments/assets/abc479f3-4c50-486f-95b8-a6989238ef45)

**Comment by guillermohor** [comment]
Thankyou!
