### ISSUE TITLE
Value for cooling too high - Can't set real values until machine limits.

### ISSUE THREAD

**Issue by Hammerhand17** [kamaradclimber/heishamon-homeassistant#236]
** Versions **

- Home Assistant version (for instance 2023.9): 2024.7.4
- This integration version (for instance 1.1.0): 1.4.1

**Describe the bug**

The minimum temperature I can set cooling for my machine is 15ºC when in the machine I can set it down to 5ºC. This lead to errors with automations when I try to set the temp lower than the integration lets me.

**To Reproduce**
1. Go to the integration -> aquarea zone 1 climate cooling.
2. Click on "-". The lowest value it lets is 15. If I go to the machine I can lower it down to 5ºC.

**Expected behavior**

Shoud let this value go till 5 degrees.

My machine is an aquarea kit-WC12H6E5-CL

**Comment by kamaradclimber** [comment]
Should be fixed by 1.12.5
