### ISSUE TITLE
Expose climate entities for each "room" zone

### ISSUE THREAD

**Issue by kamaradclimber** [kamaradclimber/heishamon-homeassistant#25]
Difficulty of this issue is to solve correctly the two options to control room temperature: "compensation curve" and "direct mode". This is especially complex because we can only detect at runtime (when receiving an mqtt message with the mode) which kind it is.

My own heatpump is using compensation curve so I'll start with this one (this is also the most difficult to model since it depends on many parameters).

**Comment by PGnl** [comment]
Can we disable/ enable these equal to the sensors? If yes, who not add both and give them names including “direct” and “curve”
Then people need to chose.
Or can we couple the temperature max/min to topic TOP 76
IF direct THEN min max =
ELSE curve THEN min max =

**Comment by geduxas** [comment]
Yes heishamon will update only changes, but there is setting to retransmit all values. So heishamon should retransmit required topic's..  also mqtt server will hold last value.. so don't think there's much problem's about it.

**Comment by PGnl** [comment]
Not sure I get the issue. You need mqtt messages to come in to be able to setup your integration. As such, the massage for direct or compensation should already be there.
Just checked it in a clean install. 
first install broker and mqtt integration. 
heat pump powered on. 
Messages come in, including the topic on what mode. 

So only prerequisite is that messages should have shown up before installing your sublime integration ;)

should be a simple one. 
And if nothing shows up, reload the integration after making sure messages come in.
