### ISSUE TITLE
Heishamon unit replacement and HA entity names configuration

### ISSUE THREAD

**Issue by Polosaz** [kamaradclimber/heishamon-homeassistant#255]
I wanted to ask a question. 

Do you know if I change my Heishamon unit for another, for example put in one of the new large units... do I have to reconfigure all the Home Assistant entities again? Or does it replace the ones I already have with the new ones without changing names (friendly names, entity name or anything? I understand that I need to keep the same configuration on the Heishamon unit website with exactly the same name and the rest of the parameters.

Thanks

**Comment by geduxas** [comment]
Yes you are safe till you mqtt name is the same

**Comment by Polosaz** [comment]
Ok, perfect. Thank you.

**Comment by kamaradclimber** [comment]
Thanks geduxas for the answer. Indeed, the identifier for heishamon integration is the mqtt prefix. If you keep it the same, you keep your integration untouched, otherwise it will be detected as a new install.
