### ISSUE TITLE
Set Aquarea Outlet Target Temperature from the integration

### ISSUE THREAD

**Issue by LarsMudde** [kamaradclimber/heishamon-homeassistant#256]
I'd like to be able to make functions such as the softstart from edterbak's NodeRed dashboard but directly in HomeAssistant. 
To be able to do this it would be great if I could set the Outlet Target Temperature directly from the integration as a Configuration item (but maybe also keep the existing Sensor) rather than posting on an MQTT topic manually. 

If you guys thinks this adds value or agree with me adding this, I will try to make it myself and open a PR if everyone is okay with that?

**Comment by tommeh1337** [comment]
I would love this! Currently the outlet target temp cannot be set when the sensor setting is on internal thermostat.

**Comment by geduxas** [comment]
There is much more to import from ED.. special waiting for Solar DHW and temperature control

**Comment by LarsMudde** [comment]
Yes, but if we add the configuration items to the integration people could add those kinds of things using automations if they wanted to. For now changing the target setpoint is kind of essential for me before I could fully switch to Home Assistant, therefore I'm looking into adding this myself through a PR if the owner of this repo is open to it.

**Comment by geduxas** [comment]
I am little bit sceptic about soft start function, for me it didn't work, or i have expected little bit more..

**Comment by tommeh1337** [comment]
But even without the soft start it would make sense to implement this.

I can’t change the outlet target temp from within HA when I use the controller as internal thermostat. This is supported in Panasonic Service Cloud and Node Red though.

Currently I can only change the outlet target temperature when the zone 1 sensor setting is on “water”.

**Comment by geduxas** [comment]
It seam's to bug for me, why it's not possible? Component disabled or what?

**Comment by tommeh1337** [comment]
Because the same entity is used for both the internal thermostat set temperature as the outlet set point.

`climate.panasonic_heat_pump_main_z1_temp`

**Comment by LarsMudde** [comment]
<html><body>

TOP7 | Main_Target_Temp | 41 | °C
-- | -- | -- | --



</body>
</html>
<html><body>

TOP29 | Z1_Heat_Curve_Target_High_Temp | 41 | °C
-- | -- | -- | --



</body>
</html>
<html><body>

TOP42 | Z1_Water_Target_Temp | 41 | °C
-- | -- | -- | --



</body>
</html>
I see 3 topics related to this, so you are saying that I should be able to get by setting only the:
climate.panasonic_heat_pump_main_z1_temp
When running with an external room Thermostat on CN2 ?

**Comment by kamaradclimber** [comment]
@LarsMudde yes I would be glad to get a PR on this. I'm not sure which mqtt topic would be used to set this.
Send me a PR and I'll review it.

**Comment by geduxas** [comment]
> TOP7 | Main_Target_Temp | 41 | °C -- | -- | -- | --
> TOP29	Z1_Heat_Curve_Target_High_Temp	41	°C
> TOP42	Z1_Water_Target_Temp	41	°C
> I see 3 topics related to this, so you are saying that I should be able to get by setting only the: climate.panasonic_heat_pump_main_z1_temp When running with an external room Thermostat on CN2 ?
> Edit: Edterbak's dashboard posts on the following topics:
> 
> Fri Oct 4 15:39:02 2024 (1119231530): received TOP7 Main_Target_Temp: 37 Fri Oct 4 15:39:02 2024 (1119231533): received TOP29 Z1_Heat_Curve_Target_High_Temp: 37 Fri Oct 4 15:39:02 2024 (1119231536): received TOP42 Z1_Water_Target_Temp: 37

Not all topics are settable, panasonic accepts set bits only for first 130bytes (around that) topics are not related to byte location. 
Main target temp is for main outlet, z1 target temp is target temp for zone 1 in multi-zone mode. While it's single zone and without buffer tank it will remain same as main target temp. And heat curve target high temp is curve set point.. it's only are settable in current list of sensors.
