### ISSUE TITLE
Aquarea Heat Model not recognized

### ISSUE THREAD

**Issue by thecem** [kamaradclimber/heishamon-homeassistant#260]
** Versions **

- Home Assistant version: 2024.12.3
- This integration version: 1.3.4

**Describe the bug**

I have a IG:WH-ADC0509L3E5AN AG:WH-WDG05LE5  and the Model is not shown in HA

**Comment by kamaradclimber** [comment]
Hello,
it should be fixed in https://github.com/kamaradclimber/heishamon-homeassistant/releases/tag/1.13.5
