### ISSUE TITLE
DHW value logic

### ISSUE THREAD

**Issue by geduxas** [kamaradclimber/heishamon-homeassistant#30]
https://github.com/kamaradclimber/heishamon-homeassistant/blob/17e568b6d326f2e206ecc5c8ef4adc69abfa2b79/custom_components/aquarea/climate.py#L157-L172

For the 3 mode, I think would be best to switch off pump. If there is last option to heat DHW and you switch it off pump should turn off and that's it. 
vice versa and with room thermostats, if DHW is not installed and you switch off heating for all zones, pump should turn off.

**Comment by PGnl** [comment]
I think I get what you mean, but I believe that is not in line with normal logic.
That is what the main switch on/off is for.
I would be careful changing the logic of the heat pump in a standard setup.
If this is really wanted, I would make “3” reliant on topic 100.

**Comment by kamaradclimber** [comment]
I am also not fond of switching off the pump altogether. Ill try to find a better way

**Comment by geduxas** [comment]
> I am also not fond of switching off the pump altogether. Ill try to find a better way

Why not? If heatpump left only DHW heating option, and user for some reason desides to switch it off.. so nothing left to heat. Then logical step would be to turn off pump.. it could be combined with that switch.

and same behavior heating/cooling in zones. For example you have Heat + DHW in 2 zone settings. If you turn off DHW, you left with Heating only, if you turn off 1 zone, you left with heating and second zone only.. after turning off last zone, nothing left to heat.. so pump should turn off..

**Comment by PGnl** [comment]
I would love to, but do not have DHW myself ;)
Not sure how that would work.
