### ISSUE TITLE
Multiple heat pumps?

### ISSUE THREAD

**Issue by whulshof** [kamaradclimber/heishamon-homeassistant#41]
Can i just add a second Aquarea heat pump with its own heishamon board? How to distinguish between them?

**Comment by geduxas** [comment]
I think it should work, 2days ago author made changes for that

**Comment by whulshof** [comment]
can I just fill in the same matt topic base? "panasonic_heat_pump"?

**Comment by whulshof** [comment]
I don't want to end up with a ton of extra entities, that are not distinguishable

**Comment by geduxas** [comment]
Sorry, i am bit confused. For now only one pump will work.

**Comment by kamaradclimber** [comment]
At the moment, indeed the integration works with a single heatpump.
Supporting multiple heat pumps would require a bit of refactoring in the integration.

**Comment by whulshof** [comment]
That is a pity. One HP would not be enough for getting "off of the gas".

**Comment by geduxas** [comment]
> That is a pity. One HP would not be enough for getting "off of the gas".

Do you use them separately or in cascade mode? In cascade mode both should work as one.. no?

**Comment by PGnl** [comment]
Or for the time being, add one in yaml. And only add what you need. Then in the future, you step over when it becomes available. 
just need to change the topic in all the items in the yaml file to whatever main topic you want and use that topic in the Heishamon as well.

Agree, not as simple/ elegant, but for now that would work.

**Comment by whulshof** [comment]
> > That is a pity. One HP would not be enough for getting "off of the gas".
> 
> Do you use them separately or in cascade mode? In cascade mode both should work as one.. no?

They both work in parallel. One is mostly doing the DHW function and if it really gets cold it helps in heating. The other only does the heating. So they are not aware of each other. So separately.

**Comment by kamaradclimber** [comment]
You can try the 0.9.0 pre-release of this integration, I've added experimental support for multiple heatpumps.
The remaining element is to be able to distinguish entities in UI. For now I've not done anything in that direction (it means you'll likely have to hide a lot of entities from your "Everything" dashboard).

**Comment by whulshof** [comment]
Nice! Thanks a lot. I will try ASAP, probably tonight. Fingers crossed!

**Comment by whulshof** [comment]
It does work, but not the first time. I doubled all my entities the first time. For one reason or another, the second time it recognised the topic name (panasonic_heat_pump-1) of the second heishamon board. I'm fine now. 
Great many thanks!!

**Comment by kamaradclimber** [comment]
I'm closing the issue (I've fixed one issue in 0.9.1 to facilitate migration between < 0.9.0 and latest version).
Let me know if you still encountered bug of course.
