### ISSUE TITLE
Riemann Integral for heat/dhw Energy Consumption for Energy Dashboard

### ISSUE THREAD

**Issue by Bucky2k** [kamaradclimber/heishamon-homeassistant#51]
Integration proposal:

In order to show heat and dhw energy consumption of the heat pump as individual devices in the energy dashboard, I added the following to my configuration:

`sensor:  #Calculation Energy consumed (kWh) - DHW
  - platform: integration
    source: sensor.panasonic_heat_pump_main_dhw_energy_consumption
    name: Aquarea DHW Energy Consumed
    round: 1
    unit_prefix: k
    method: left
  #Calculation Energy consumed (kWh) - Heat
  - platform: integration
    source: sensor.panasonic_heat_pump_main_heat_energy_consumption
    name: Aquarea Heat Energy Consumed
    round: 1
    unit_prefix: k
    method: left`

**Comment by kamaradclimber** [comment]
Would you be interested in adding those to the integration? I would definitely take a PR for this :)

**Comment by Bucky2k** [comment]
Can you point where roughly this would have to be entered in your files/code? Never created an integration myself. The code above is placed in the configuration.yaml in my current case

**Comment by kamaradclimber** [comment]
https://github.com/kamaradclimber/heishamon-homeassistant/blob/main/custom_components/aquarea/sensor.py#L77 would be the right place to add the object representing the entities.

[Here](https://github.com/home-assistant/core/blob/dev/homeassistant/components/integration/sensor.py#L176) is how HA declare the `IntegrationSensor`s defined via the UI.
