### ISSUE TITLE
Watthours - suppress decimals

### ISSUE THREAD

**Issue by Bucky2k** [kamaradclimber/heishamon-homeassistant#52]
I suggest to suppress the decimals for the S0 Watthours
![Screenshot_20221122_120245_Home Assistant](https://user-images.githubusercontent.com/67497826/203298440-fb1ac8ec-2d3f-4016-aae5-60d388bda85b.jpg)

**Comment by Bucky2k** [comment]
PS: I know a pull request ist better than posting just the issue - I will try to contribute as soon as possible

**Comment by Bucky2k** [comment]
Any feedback on this, does it make sense? Should be only a format filter at the right places

**Comment by kamaradclimber** [comment]
I'm ok with it. Don't hesitate to build a PR and we'll discuss on it.

**Comment by Bucky2k** [comment]
@geduxas No change regarding the numeric format (still Wh with two always zero decimals) after the change, correct? Or should it have changed? Nothing visible on my side

**Comment by geduxas** [comment]
> @geduxas No change regarding the numeric format (still Wh with two always zero decimals) after the change, correct? Or should it have changed? Nothing visible on my side

it should change from Wh to kWh.. didin't ?

**Comment by geduxas** [comment]
i think i messed with items while testing :/

**Comment by kamaradclimber** [comment]
https://developers.home-assistant.io/blog/2023/01/25/sensor_rounding/ might help with this (I'll test when 2023.2 will be out)
