### ISSUE TITLE
Maximum Target temperature limited to 25 degree

### ISSUE THREAD

**Issue by Striker2102** [kamaradclimber/heishamon-homeassistant#59]
Hello, first one thank you for this nice integration.

at the moment my panasonic is working on fixed target temperature.

when i would like to set the target temperature from Homeassistant, the maximum of climate.panasonic_heat_pump_main_z1_temp is 25

i can´t set the target temperature over dashboard to higher of 25. is possible to change this?

![image](https://user-images.githubusercontent.com/74838469/206207964-43cc9c94-2dea-4362-86f2-0d167b350e4b.png)

and the same for the target senor
![image](https://user-images.githubusercontent.com/74838469/206208133-45f6eee4-aa03-43b9-adc9-5556da61a934.png)

![image](https://user-images.githubusercontent.com/74838469/206208416-55eea7da-2d51-4558-8eda-24ba81ed9063.png)

thank you

**Comment by geduxas** [comment]
For now there is some issues with direct temperature settings.. so please wait for solution :)  duplicate issue in #57

**Comment by kamaradclimber** [comment]
It should be fixed in 0.9.6
