### ISSUE TITLE
Cannot be found on hacs

### ISSUE THREAD

**Issue by chmadkk** [kamaradclimber/heishamon-homeassistant#62]
Hi.
The integration is not showing up in the hacs integrations store.
Am i doing something wrong ?

**Comment by PGnl** [comment]
It is a custom repository.
As such one needs to put a link in the HACS menu to :
https://github.com/kamaradclimber/heishamon-homeassistant

In HACS, go to [integrations] , then top richt corner the three dots.
Then choose custom repository. 

at the bottom paste the link from above to kamaradclimbers repository.
Value below choose integration 

Click add 😁

now it is in HACS and enjoy

**Comment by chmadkk** [comment]
Thanks then. Clarified it for me :-)

søn. 11. dec. 2022 11.31 skrev PGnl ***@***.***>:

**Comment by kamaradclimber** [comment]
The integration is waiting for https://github.com/hacs/default/pull/1548 to be merged (but it has been a long time and I don't have feedback yet)
