### ISSUE TITLE
MQTT connected, Hassio integration unknown

### ISSUE THREAD

**Issue by LaMiyu** [kamaradclimber/heishamon-homeassistant#63]
Hello,

I don't know if I'm doing something wrong or if it's actually a problem at the moment?

I set Heishamon according to my MQTT data.
![image](https://user-images.githubusercontent.com/73053267/206929031-86061192-e1e4-4ee5-b6ba-d8d277684362.png)

It is also displayed in the MQTT log of my HA:
![image](https://user-images.githubusercontent.com/73053267/206929063-3b2771cf-3ce4-4eda-beec-182ba318a088.png)

When I add the Heishamon integration, it doesn't recognize any values, all unknown.
Since it should be recognized automatically, I'm at a loss ;(
![image](https://user-images.githubusercontent.com/73053267/206929093-ac716aa3-84eb-43c0-8733-40366878318f.png)
![image](https://user-images.githubusercontent.com/73053267/206929102-dcee3619-687d-4793-a4c7-6daafda44023.png)
![image](https://user-images.githubusercontent.com/73053267/206929122-051706b2-68db-40c2-b473-556ca1068296.png)

**Comment by PGnl** [comment]
Do you have mqtt up and running on your home assistant?
This needs to be done first. Or a Broker on a different device.
If yes, please use “mqtt explorer” (use Google) and log in with the credentials of your mqtt broker and see if everything is coming in.
Based on the info, you either have not completed your mqtt setup, or your credentials (password and login) for the mqtt broker is wrong. 

I use the “mosquitto“ add-on. 😉

**Comment by LaMiyu** [comment]
Hello,

yes - the screenshot: „client connected“
This ist from mosquitto Log directly in HA

**Comment by PGnl** [comment]
Sorry, missed that one Image (Bit small on my phone)

**Comment by geduxas** [comment]
@LaMiyu do you see updated values in Heishamon itself? Also as @PGnl suggest could you check with mqtt explorer are values correctly updated in mqtt server..

**Comment by LaMiyu** [comment]
Good morning, 

thank you both for the feedback. 

Yes, in Heishamon I can see the current data, which also changes regularly. 

I'll check that with the MQTT Explorer this afternoon, unfortunately I'm working for now. 

When I set up heishamon in HA for the first time, I set an incorrect user for the MQTT in Heishamon - during the initial setup, the process of initialization & setup also took much longer - if I now delete Heishamon, also from HACS, then reinstall it, the initialization takes time only a few seconds - could it also simply be that there is still an incorrect config somewhere from the first installation that is now being used and is not removed when uninstalling? 

Thanks very much!

**Comment by LaMiyu** [comment]
Hello,

I have now installed MQTT Explorer.

I entered the IP of the HA and as user/PW the same data as in Heishamon - it works:
![image](https://user-images.githubusercontent.com/73053267/207055335-b6759fb0-b703-4810-ba43-fa121e874d8e.png)


Anyone have an idea where the problem is?

**Comment by LaMiyu** [comment]
.. I have now downloaded and activated 0.9.5 from HACS instead of the current 0.9.7:

here came an additional window when setting up and I could directly select the correctly recognized Heishamon or alternatively configure one manually....

I didn't have this window with 0.9.7?

- it's fixed for me, everything works with 0.9.5 :=)

**Comment by kamaradclimber** [comment]
The `via None topic` seems to happen when you don't have a MQTT server connected to HA (at least I can reproduce the issue that way).
And you have big errors in HA logs:
```
homeassistant.exceptions.HomeAssistantError: Cannot subscribe to topic 'Nonemain/Pump_Flow', MQTT is not enabled
```

I can have a look at how we could interrupt the setup flow when facing this issue.

**Comment by kamaradclimber** [comment]
I think #64 will fix the (incorrect) configuration path you've probably taken.
The expected path is:
- setup HeishaMon and MQTT
- the integration is "discovered" automatically and you just have to accept installation

**Comment by kamaradclimber** [comment]
I'll close the issue but feel free to comment if you feel it's not solved and I'll re-open if necessary
