### ISSUE TITLE
Aquarea Zone 1 climate max temperatur

### ISSUE THREAD

**Issue by andriuskr** [kamaradclimber/heishamon-homeassistant#66]
Currently Aquarea Zone 1 climate max temperature is 25'C. As it is temperature of water going to underfloor heating, this setting is too low. It should be max 45'C

This also is relevant to Aquarea Zone 2 climate, but in my setup zone 2 is not used

**Comment by kamaradclimber** [comment]
https://github.com/kamaradclimber/heishamon-homeassistant/releases/tag/0.9.9 should help.
Thanks for the report

**Comment by kamaradclimber** [comment]
see also #57
