### ISSUE TITLE
Switch symbol behavior for holiday mode

### ISSUE THREAD

**Issue by Bucky2k** [kamaradclimber/heishamon-homeassistant#75]
Hi,

I oberserved a strange behavior of the holiday mode switch. If operated from HA, the switch is shown as a usual left/right slider. If it gets it's status from Heishamon, it changes to the flash / electricity symbol. Operating it again from HA, it shows the slider again. 

Local problem of my installation? 

Br 

Bucky

![Screenshot_20221225_100938_Home Assistant](https://user-images.githubusercontent.com/67497826/209462704-306bc6d4-fa8d-46e5-9e3f-45e605fa73f2.jpg)

**Comment by Bucky2k** [comment]
It seems there exists a workaround, but I prefer of course to find the root cause. It's something around an unclear "assumed state" I guess:

https://community.home-assistant.io/t/some-switches-use-the-flash-icon-instead-of-a-switch-icon/222409

**Comment by Bucky2k** [comment]
Wurde unbekannt --> became unknown (few seconds after it showed correct status & symbol after changing mode on Aquarea)

![Uploading Screenshot_20221225_102923_Home Assistant.jpg…]()

**Comment by Bucky2k** [comment]
Wurde unbekannt --> became unknown (few seconds after it showed correct status & symbol after changing mode on Aquarea)

![Screenshot_20221225_102923_Home Assistant](https://user-images.githubusercontent.com/67497826/209463013-025cdc4d-ee09-4c92-828e-e390287b40be.jpg)

**Comment by Bucky2k** [comment]
Got it: Holiday Mode has three status values: 

Holiday mode (0=off, 1=scheduled, 2=active)

Mode 2 / active is not properly captured

So the flash symbol only comes up, when the holiday mode becomes active at scheduled time

**Comment by kamaradclimber** [comment]
Good catch. We now need to find the proper entity to reflect this. 
My first idea is to split between entities:
- one showing the holiday mode status (3 possible states)
- one switch to configure holiday mode

**Comment by Bucky2k** [comment]
I think this is adequate, as we cannot "force" state active anyway. So On/off as a slider and the three states just read only

**Comment by sermayoral** [comment]
> Good catch. We now need to find the proper entity to reflect this. My first idea is to split between entities:
> 
>     * one showing the holiday mode status (3 possible states)
> 
>     * one switch to configure holiday mode

Hi. First of all, thank you very much for this custom component :-)

Could the same thing happen with defrost? I had a defrost sensor (TOP26) that I use to know when the pump goes into defrost mode. In this component I find a switch and no sensor.

**Comment by geduxas** [comment]
> 

Yes but it will turn on in defrost mode.. also it will be in history of that switch.. is it some problems with that?

**Comment by Bucky2k** [comment]
Defrost switch works as expected on my side

**Comment by sermayoral** [comment]
> > 
> 
> Yes but it will turn on in defrost mode.. also it will be in history of that switch.. is it some problems with that?

You mean, this switch turns on when the pump goes into defrost mode. Beside that, you can force the pump to startt the defrost mode turning on the switch. Don't you?

**Comment by geduxas** [comment]
> > > 
> > 
> > 
> > Yes but it will turn on in defrost mode.. also it will be in history of that switch.. is it some problems with that?
> 
> You mean, this switch turns on when the pump goes into defrost mode. Beside that, you can force the pump to startt the defrost mode turning on the switch. Don't you?

yes, it's shows state and you can  force set state.. If pump decides to defrost, so state of defrost will trigger switch on. And if you wan't force to defrost, you click on it.

**Comment by sermayoral** [comment]
Thanks @geduxas. No problem with that behaviour
