### ISSUE TITLE
device_class: running in some entities

### ISSUE THREAD

**Issue by sermayoral** [kamaradclimber/heishamon-homeassistant#77]
Hi!! I found some entities of this component with the device_class set to 'running'. 

I think this kind of device class is designed for process or threads that can being executing or not (running or not running). For example a Home Assistant addon is running, but a switch or a pump is not running. A pump is on or is off.

For example the 'Aquarea Main Power' switch has the device_class 'running', but a switch musnt'n have this device_class: https://www.home-assistant.io/integrations/switch/#device-class

**Comment by kamaradclimber** [comment]
Hello,

I understand what you mean. Indeed the running device_class is not explicitly mentioned as possible device class by the documentation. Do you some some (visual or behavioral) downsides with the current setup?

I have considered switch entities as natural extension of  binary sensors (with the addition that you can control it) so it made sense.

Regarding the semantic, I am not a native speaker, however a "running" pump feels ok to me. I'll research to see if there is something more appropriate.

**Comment by sermayoral** [comment]
@kamaradclimber thanks por your answer. Yes, my problem is that i have an automation that alert me when a software instance is not running. The automation inspects the entities which device class is running. 

It has been stranger to get an alert because my pump is not "running"... So i've decided to open this issue. In my opinion, the pump is not working or the pump is powered off. Device class "running" is being used for addons or software instances, but not for a machine. 

I can exclude heishamon entities from my automation, but i thought it deserves to discuss this theory in an issue. I could be wrong.

Thanks!

**Comment by kamaradclimber** [comment]
Thanks for the context.
I looked at other device_class without finding anything more appropriate. I also checked the semantics, it makes sense to say a heatpump is "running" (or any mechanical process apparently).
I understand it makes your automation a bit more complex (and kudos for the automated discovery of addons). 

For the time being I'll keep the code as-is. We can of course reconsider the discussion in the future.

**Comment by sermayoral** [comment]
@kamaradclimber it's ok. No problem for my automation.

Only for curiosity. For my understanding. What are the advantages of consider a power switch as a "running" entity? Consider that no other 'switch' type entity is. Or at least I had never seen it.
