### ISSUE TITLE
1.0.4. Linked to future release of 2023.3

### ISSUE THREAD

**Issue by PGnl** [kamaradclimber/heishamon-homeassistant#82]
1.0.4 is linked to HA 2023.3 
Believe that this should be linked to 2023.2 
Rounding of decimals had already been added to 2023.2. Cannot find reason to link to the future release of 2023.3.
Could it be a typo?
If not, please close 😉

**Comment by Bucky2k** [comment]
...had the same thought

**Comment by kamaradclimber** [comment]
It's a typo indeed, let me fix it

**Comment by kamaradclimber** [comment]
Fixed by https://github.com/kamaradclimber/heishamon-homeassistant/releases/tag/1.0.5

**Comment by kamaradclimber** [comment]
thanks for the report

**Comment by PGnl** [comment]
Thanks kamaradclimber.
