### ISSUE TITLE
Update to latest version

### ISSUE THREAD

**Issue by root2k** [kamaradclimber/heishamon-homeassistant#84]
Sorry for this comment but I'm using the integration not so long and since the installation on HA HACS I didn't do any update.
So could someone tell me how to update on Home Assistant to the latest version?
Am I right that the version 1.5 of heishamon-homeassistant implemants the Heishamon v.3.1 of Egyras?

**Comment by geduxas** [comment]
Just download all source, and manually overwrite in custom_components folder
