### ISSUE TITLE
Missing kWh-device(s)

### ISSUE THREAD

**Issue by Maarten69** [kamaradclimber/heishamon-homeassistant#86]
Before latest update I had 132 entities, now 130.
I'm missing the custom kWh devices:

- sensor.panasonic_heat_pump_s0_watt_1
- sensor.panasonic_heat_pump_s0_watthourtotal_1

Did you change something?

**Comment by kamaradclimber** [comment]
Could it come from https://github.com/kamaradclimber/heishamon-homeassistant/commit/ab23692fe92f79399f7fed1a4c721c7c94d35d80 ?
Could you remove those lines, restart HA and compare?

Also could you confirm the version of HA you use please?

**Comment by PGnl** [comment]
I have the same. But not after an update of the HACS repository.
Happened yesterday after update to latest HA core. Core.2023.2.5

**Comment by BurgerMario** [comment]
Delete in /config/custom_components/aquarea/sensor.py
Line 268 native_precision=0
and the other in 279 ( the same)

Save and reboot HA..

**Comment by simplyjeroen** [comment]
for me it is line 268 and 281. but that indeed solves the problem

**Comment by BurgerMario** [comment]
OK, sorry... The Line 268 and 281 is right ;)

**Comment by kamaradclimber** [comment]
Do you see the same issue with HA core 2023.3 ?

**Comment by BurgerMario** [comment]
Yes!! Delete Row 268 an 281, then your problem is gone :)

**Comment by simplyjeroen** [comment]
the problem came to me the moment I update to 2023.3

**Comment by BurgerMario** [comment]
The problem comes first with the HA 2023.3 ...
A brand new restart dialog, ask Assist about the state of your home, amazing new dialogs for lights and switches, Thread & Matter updates, **control the precision of your sensors**

**Comment by kamaradclimber** [comment]
https://developers.home-assistant.io/blog/2023/02/08/sensor_presentation_rounding/ mentions that [native_precision](https://developers.home-assistant.io/blog/2023/01/25/sensor_rounding) addition has been reverted.

I can reproduce locally and will fix the issue.
