### ISSUE TITLE
Missing S0 sensors since HA 2023.3 update

### ISSUE THREAD

**Issue by vandermark1977** [kamaradclimber/heishamon-homeassistant#87]

**Comment by vandermark1977** [comment]
I get error in the log regarding the S0 sensors:

`Logger: homeassistant.util.logging
Source: util/logging.py:168
First occurred: 21:32:53 (62 occurrences)
Last logged: 21:37:44

Exception in message_received when handling msg on 'panasonic_heat_pump/s0/Watt/1': '894' Traceback (most recent call last): File "/config/custom_components/aquarea/sensor.py", line 260, in message_received description = HeishaMonSensorEntityDescription( TypeError: HeishaMonSensorEntityDescription.__init__() got an unexpected keyword argument 'native_precision'
Exception in message_received when handling msg on 'panasonic_heat_pump/s0/Watt/1': '896' Traceback (most recent call last): File "/config/custom_components/aquarea/sensor.py", line 260, in message_received description = HeishaMonSensorEntityDescription( TypeError: HeishaMonSensorEntityDescription.__init__() got an unexpected keyword argument 'native_precision'
Exception in message_received when handling msg on 'panasonic_heat_pump/s0/Watt/1': '893' Traceback (most recent call last): File "/config/custom_components/aquarea/sensor.py", line 260, in message_received description = HeishaMonSensorEntityDescription( TypeError: HeishaMonSensorEntityDescription.__init__() got an unexpected keyword argument 'native_precision'
Exception in message_received when handling msg on 'panasonic_heat_pump/s0/Watt/1': '891' Traceback (most recent call last): File "/config/custom_components/aquarea/sensor.py", line 260, in message_received description = HeishaMonSensorEntityDescription( TypeError: HeishaMonSensorEntityDescription.__init__() got an unexpected keyword argument 'native_precision'
Exception in message_received when handling msg on 'panasonic_heat_pump/s0/Watt/1': '889' Traceback (most recent call last): File "/config/custom_components/aquarea/sensor.py", line 260, in message_received description = HeishaMonSensorEntityDescription( TypeError: HeishaMonSensorEntityDescription.__init__() got an unexpected keyword argument 'native_precision'`

**Comment by BurgerMario** [comment]
https://github.com/kamaradclimber/heishamon-homeassistant/issues/86

Same höre…

**Comment by vandermark1977** [comment]
I think it has maybe to do with the new display precision settings for sensors?

https://www.home-assistant.io/blog/2023/03/01/release-20233/#sensor-display-precision

**Comment by PGnl** [comment]
This is the same as issue #86 
Please keep to one location.

**Comment by kamaradclimber** [comment]
Let's continue the discussion in #86 . Thanks for the logs @vandermark1977
