### ISSUE TITLE
auto-discovery issue ?

### ISSUE THREAD

**Issue by Giga77** [kamaradclimber/heishamon-homeassistant#89]
Hi

I bought a HeishaMon communication PCB and I configured it.
And now I can see the values in MQTT Explorer:
![image](https://user-images.githubusercontent.com/2777446/228318536-fdc0dd41-9357-4942-ace9-edb1e6d1581f.png)

But in HA, the HACS integration is intalled, but it doesn't appear in integrations tab  and the sensors aren't created:
![image](https://user-images.githubusercontent.com/2777446/228320310-eda4c25f-5394-44aa-8f88-047f37118c11.png)

I'm able to create manually MQTT sensors related with the topic "panasonic_heat_pump".

## System Information

version | core-2023.3.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.10
os_name | Linux
os_version | 5.15.84-v8
arch | aarch64
timezone | Europe/Paris
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4883
Installed Version | 1.31.0
Stage | running
Available Repositories | 1250
Downloaded Repositories | 16

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.03.2
agent_version | 1.4.1
docker_version | 20.10.22
disk_total | 439.4 GB
disk_used | 24.4 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.5.0), Samba share (10.0.0), Terminal & SSH (9.6.1), Log Viewer (0.15.0), Mosquitto broker (6.1.3), Node-RED (14.1.1), Vaultwarden (Bitwarden) (0.19.2), Samba Backup (5.2.0), Let's Encrypt (4.12.8), Uptime Kuma (0.7.1)

</details>

**Comment by PGnl** [comment]
After installation in HACS you need to also “install” the repository in HA as well. In HA go to settings, devices and services and go to the big blue button saying “add integration” 
Search for Heishamon and install. 
HACs only adds the integration to the available integrations within HA, but does not do an auto install as far as I remember.

**Comment by kamaradclimber** [comment]
If it still does not work, it might be necessary to set the log to debug level and scan for "heishamon" string hoping to find something relevant.

**Comment by Giga77** [comment]
I re-install the repo, and now I have a discovered heishamon.
![image](https://user-images.githubusercontent.com/2777446/228332753-6f097346-f309-48be-9d38-a2024570272d.png)
