### ISSUE TITLE
Heishamon read only

### ISSUE THREAD

**Issue by MrJoki007** [kamaradclimber/heishamon-homeassistant#93]
Hello,
im using heishamon in read only configuration.
Is there a way to set it in this integration?

**Comment by geduxas** [comment]
i think so.. integration is directly tied to heishamon MQTT topic's.. so everything what heishamon transmit are picked.. also it's possible to send values, but i am doubt that heishamon will transmit anything to pump..

**Comment by MrJoki007** [comment]
Ok, thank you.
Then i will just ignore it.
