### ISSUE TITLE
Heishamon integration does not update the values

### ISSUE THREAD

**Issue by sabom2d** [kamaradclimber/heishamon-homeassistant#94]
I have installed Heishamon Community integration, all Attributes are recognized on Installation, but I see that the Values from the HP are not updated, seems to be in a frozen state. Eg. it still shows DHW Power Consumed 1600W and DHW Power Produced 4800W although the HP is of since yesterday, so what I see, all Attributes show the Values from installation. Main Power is still on and if I switch it of, it switches on again. Anything i need to configure?

**Comment by kamaradclimber** [comment]
Hello,
You should check if values are updating on heishamon web ui. It happened to me that heishamon was simply frozen.

**Comment by sabom2d** [comment]
Hi, I have checked this and it is constantly updating, anyway, thanks for your input.

**Comment by kamaradclimber** [comment]
Do you still have the issue?
My guess is that it might disappear with a restart of HA (I don't know how it behaves if the connection to mqtt server is temporarily broken for instance)

**Comment by miriam967** [comment]
I have the same / similar issue. Heishamon is configured to get data from HP every 5s and is supossed to send data to MQTT broker every 30s. 

I do get values but not every 30s. For example, 

For Heishamon RSSI I can see a new datapoint every 30s, but for other TOPs I get the datapoints only very irregulary.
For heat_pump_main_outside (top14) I have data points for 10:16, 10:22, 10:32, 10:35, 10:41, 10:45, 10:46, 10:51, 10:52, 10:56
For inlet_temp I got data points for ever 30s, then for over an hour no data points at all (even though I get data points for other TOPs meanwhile) and then again I get data points for inlet temp again every 30s.
Comp_frequency (TOP8) is very regulary (every 30s), but it seems all the temperature tops are not (inlet/outlet temps).

Heishamon shows 99% correct received data and no MQTT reconnects. I did reboot Heishamon and HA (MQTT broker) multiple times, but the issue persists. I was wondering if data is only updated when values changes, but even then I would expect data points with just the same values.

**Comment by geduxas** [comment]
In heishamon there is gethering data, it's value represent how often to fetch values from pump, and if i remember correctly changed values imidiately updated to mqtt, second record is for retransmission. Default value is 300s in that time is how often all values are reposted to mqtt. Also make note that if you enable PCB emulation, this will get priorities.

**Comment by miriam967** [comment]
Yes, first setting (fetch data from pump) is set to 5s. Second setting (retransmission) is set to 30s.

PCB emulation is disabled.

Still, for some reason, some topics only get updates irregulary (temperature topics).

**Comment by geduxas** [comment]
So please check mqtt server with mqtt explorer or similar tool, do heishamon updates it regularly?

**Comment by miriam967** [comment]
Thank you for the help! I checked with MQTT explorer: interestingly, the broker gets updates every 30s (which is correct to the settings in Heishamon) - also for the temperature topics. However, they are not written into HA history (and HA doesnt write to influxdb).

For outlet_temperature, mqtt explorer shows data points every 30s, but in HA history I see data points:
11:44:39
11:44:44
11:44:49
11:44:54
11:44:59
11:45:04
11:46:04
11:47:29
11:48:49
11:51:19
11:54:14
11:57:09
11:57:19
12:00:39
12:01:19
12:04:54

I cannot see any pattern... 

For outside temp I see updates in mqtt explorer every 30s - constant 12 °C.
In HA I see updates:
11:35:43
11:44:09
11:44:29

And no other data point for the last 20 minutes.

**Comment by geduxas** [comment]
I also use HA to Influxdb.. yes HA updates values only on change. So i am picking values direct from mqtt to Influxdb

**Comment by miriam967** [comment]
Ok, that explains it, since outside temp doesnt change. Thank you :) that solves a mystery.

May I ask how you push data from mqtt directly to influxdb? Do you use a telegraf instance to do so?

**Comment by geduxas** [comment]
Yes through telegraf

**Comment by kamaradclimber** [comment]
Initial issue from @sabom2d was regarding value that were supposed to change (like power consumption)

**Comment by sabom2d** [comment]
Hi, my Initial Issue is solved after resetting everything ( even the mqtt broker ), not clear what the real root cause was.

**Comment by sabom2d** [comment]
Hi, my Initial Issue is solved after resetting everything ( even the mqtt broker ), not clear what the real root cause was.

**Comment by sabom2d** [comment]
Hi, my Initial Issue is solved after resetting everything ( even the mqtt broker ), not clear what the real root cause was.

**Comment by sabom2d** [comment]
Thanks kamaradclimber, indeed, I had to restart all systems, even the MQTT broker and after that issue was solved, although I'm not sure, what the root cause was now.
