### ISSUE TITLE
Unable to prepare setup for platform aquarea.sensor: Platform not found 

### ISSUE THREAD

**Issue by krispek** [kamaradclimber/heishamon-homeassistant#98]
After upgrading HA to 2023.9.0, the Heishamon integration does not load. I get the following error:
```
Unable to prepare setup for platform aquarea.sensor: Platform not found (No module named 'homeassistant.helpers.template_entity').
```
Do others recognise this? Is this something I can resolve myself?

**Comment by giedriuskilcauskas** [comment]
I have the same issue:
I've removed: 
https://github.com/kamaradclimber/heishamon-homeassistant/blob/main/custom_components/aquarea/sensor.py#L23
and 
https://github.com/kamaradclimber/heishamon-homeassistant/blob/main/custom_components/aquarea/sensor.py#L74-L207
Also modified:  https://github.com/kamaradclimber/heishamon-homeassistant/blob/main/custom_components/aquarea/sensor.py#L52-L54
to be only: `all_sensors = real_sensors`
After restarting, seems to work.

There seems to be a breaking change in 2023.9 related to that helper

**Comment by lolobar** [comment]
Same here

**Comment by ahamro** [comment]
Me too. I'll try what @giedriuskilcauskas did and see if that works for me.

**Comment by giedriuskilcauskas** [comment]
> > > Me too. I'm rather new here so I have to ask: how can I try what @giedriuskilcauskas changed ? Just edit the files and restart?
> > 
> > 
> > yep. I've used VSCode addon, but you can do that with File Editor one as well
> 
> could you contribute and push changes ? :)

I can contribute by removing non working piece, but there is #90 which was targeting to fix it in some way. So if removing (or commenting out) is what we all want, I can do that.

**Comment by ahamro** [comment]
I edited the sensor.py file and the integration is working for me now. Thanks @giedriuskilcauskas !

I don't know exactly what functionality is missing now due to the edit but I hope it can be restored in the future.
Isn't @kamaradclimber available anymore?

**Comment by giedriuskilcauskas** [comment]
> I edited the sensor.py file and the integration is working for me now. Thanks @giedriuskilcauskas !
> 
> I don't know exactly what functionality is missing now due to the edit but I hope it can be restored in the future. Isn't @kamaradclimber available anymore?

The missing piece is now COP calculation, which was done by dividing production/consumption

**Comment by pistunut** [comment]
In my case I have replaced:
`from homeassistant.helpers.template_entity import CONF_AVAILABILITY`
with
`from homeassistant.helpers.trigger_template_entity import CONF_AVAILABILITY`
in `sensor.py` file.
Everything worked again without the need to delete or comment out any part of the code (COP works too).

**Comment by kamaradclimber** [comment]
Thanks all for your exchanges. I've pushed https://github.com/kamaradclimber/heishamon-homeassistant/releases/tag/1.0.10 which will fix it.
